### ISSUE TITLE
Feature request - ability to localise has_one relationships

### ISSUE THREAD

**Issue by willmorgan** [tractorcow/silverstripe-fluent#103]
Maaaybe being a little cheeky here :wink: but thought I might suggest it, as it's come up as a requirement.

Basically rationale behind this is that I am linking to a video that has an English audio track on the English site, but for the Arabic version of the site, English is kinda useless - so a separate version is needed.

I tried my luck with also adding to the `$translate` array the `FileID`, but that doesn't seem to have worked with an `UploadField`.

**Comment by tractorcow** [comment]
```
CASE WHEN "SiteTree"."ClassName" IN ('MediaNode', 'FileNode', 'ImageNode', 'VideoNode')
		THEN "MediaNode"."FileID_en"
			WHEN "SiteTree"."ClassName" IN ('ImageNode')
				THEN "ImageNode"."FileID_en"
				ELSE NULL
```

This looks like a core bug not just a fluent one. `ImageNode` should not be in the first list, only the second.
