### ISSUE TITLE
Translation of URLs (url segments)

### ISSUE THREAD

**Issue by PLawitschka** [tractorcow/silverstripe-fluent#113]
Maybe I'm missing something...but URLs of the SiteTree are not beeing recognized. Is that correct and therefore a missing feature?

I have two locales:

```
locales:
    - de_DE
    - en_US
  aliases:
    de_DE: 'de'
    en_US: 'en'
```

And I have a page translated in both languages. The URLSegment is also translated in both languages and it works fine for the german page. But if I navigate to the english version...I've got an 404. In the CMS different URLs are shown for teh two pages:

de: http://yeoldekitchen.com/de/deutsche-seite
en: http://yeoldekitchen.com/en/english-page 

But only these are found:

http://yeoldekitchen.com/de/deutsche-seite
http://yeoldekitchen.com/en/deutsche-seite

Is this a bug?

**Comment by tractorcow** [comment]
Which version of fluent are you using? 3.1.0 does not have urlsegment translation enabled, as this was implemented in 3.1.1, and requires framework 3.1.1 or greater.

I've just updated the main branch to 3.2 and tagged 3.2.0 (stable), in case you want to try it out. :)

**Comment by PLawitschka** [comment]
Hmmm...ok thanks...I had an old version and updated to 3.2.0. But it still doesn't seem to work. Urlsegments are being translated in the CMS but are not recognized when navigation to it. Maybe I have aa wrong configuration...

I have this in my mysite/_config/fluent.yml:

```
---
Name: fluentconfig
---
Fluent:
  default_locale: de_DE
  locales:
    - de_DE
    - en_US
  aliases:
    de_DE: 'de'
    en_US: 'en'
---
Name: fluenti18nconfig
---
i18n:
  default_locale: de_DE
```

And this in mysite/_config/config.yml:

```
SiteTree:
  extensions:
    - FluentFilteredExtension
```

As I said...fields are being translated but the path for the translated urlsegment is not found and I get an 404 Error.

**Comment by tractorcow** [comment]
What if you remove the filtering extension? (This would leave only the actual translation extension). Is it possible you had unchecked the page in the locale causing the 404?

**Comment by PLawitschka** [comment]
Ok...just installed a fresh Silverstripe with the fluent module. It works fine and as expected. Maybe there is something wrong with my current installation.

Thanks!

**Comment by tractorcow** [comment]
Ah, good to hear. ;) Glad you could get it to work.
