### ISSUE TITLE
Problem on 3.1.12

### ISSUE THREAD

**Issue by wernerkrauss** [tractorcow/silverstripe-fluent#116]
Hi,

today i encountered a problem with SS 3.1.12:

I have a subclass of Page with own HtmlEditorField (Summary), pressing "Save" everygthing works fine, publishing afterwards it also works.

But pressing "Save and Publish" after i changed something reverts all translated fields to the original field.

Normal pages without own translated fields and direct subclasses of DataObject worked fine.

Any ideas what could be wrong?

Cheers, wmk

**Comment by tractorcow** [comment]
You could try adding

```yaml
Page:
  translate:
    - 'Summary'
```

and maybe it will force that field to translate?

If you get stuck, try to debug the DB::manipulate calls to see what is being written to the DB.

**Comment by TomasTrzil** [comment]
Hi guys, it seems I have the same sort of problem. Did you manage how to fix it?

**Comment by tractorcow** [comment]
Sorry, I haven't come across this issue... I'm hoping someone using the module will report back with the cause. :D

You'd need to report back with the values being written to your DB: You can hook into the DB::manipulate method to get this information, and Debug::dump() during a write.

**Comment by phptek** [comment]
@tractorcow @TomasTrzil  @wernerkrauss This would seem to be curiously similar to #204 and #156 no?

**Comment by tractorcow** [comment]
I bet it's the same underlying issue surfacing itself in different ways.

**Comment by phptek** [comment]
What a bar steward.

**Comment by wernerkrauss** [comment]
Just had the problem again after switching back to an oder version in history. When pressing save and publish directly after reverting i had no translation (both, german and english has english texts), if i revert, then save, and then publish, it works. I'm on Fluent 3.2.3 and SS 3.1.20

**Comment by wernerkrauss** [comment]
Might have been a configuration issue, works now. See https://github.com/tractorcow/silverstripe-fluent/issues/223#issuecomment-352699329
