### ISSUE TITLE
Class "current" menu does not work properly

### ISSUE THREAD

**Issue by bomfimjr** [tractorcow/silverstripe-fluent#117]
Hello , I have the following problem in both languages ​​the menu is not adding the class "current" correctly.

My code is like this:

```
<% cached 'navigation', List(Page).max(LastEdited), $CurrentLocale %>
    <% loop Menu(1) %>    
        <li> <a href="$Link" title="$Title.XML">$MenuTitle.XML</a></li>
    <% end_loop %>
<% end_cached %>

```

**Comment by tractorcow** [comment]
I don't see a `class=""` property in your code. Did you mean to add something like `class="$LinkingMode"`?

**Comment by bomfimjr** [comment]
Thank you, really did not pay attention to it .

**Comment by tractorcow** [comment]
Glad it worked out. :) (hopefully it did!)
