### ISSUE TITLE
GridField Translate

### ISSUE THREAD

**Issue by bomfimjr** [tractorcow/silverstripe-fluent#118]
Hello , I wonder if there is a possibility to create version for each language , grid inserts make Silverstripe

**Comment by tractorcow** [comment]
Hi, you can add the `FluentExtension` to any dataobject and you can translate them in the gridfield. You will still need to use the left-hand menu dropdown to toggle between languages though.

**Comment by bomfimjr** [comment]
I will do that , thank you.
