### ISSUE TITLE
Some localised fields not indicated as such in CMS

### ISSUE THREAD

**Issue by phptek** [tractorcow/silverstripe-fluent#122]
When some fields are localised (I can verify that the locale-appended table-columns do exist) the "LocalisedField" CSS class does not always seem to get added to the field's `<label>` element in the CMS via `updateCMSFields()`

In my example I have the following custom config in my site's `fluent.yml` file:

    field_include:
      - Title
      - MenuTitle
      - Content
      - Description
      - Caption
      - IntroHeading
      - Intro
      - Abstract
      - LinkSetsHeading
      - MegaMenuHeading

Upon logging into the CMS, I see that "Title", "MenuTitle" and "Content" all show the fluent-icon on my `SiteTree` objects (nice touch btw), but none of the others do, even though as I say above, those fields have been created in the DB itself.

**Comment by tractorcow** [comment]
Hi @phptek , you need to make sure that extensions are called on those fields after you have added them, for the extra tag to appear.

Are you adding these via extension, or are you adding them via sitetree subclasses?

If the latter, make sure that you are using `beforeUpdateCMSFields` as in https://github.com/tractorcow/silverstripe-fluent/blob/master/docs/en/dataobjects.md#default-field-scaffolder

If the former, it can be tricky to force extensions to be applied in a specific order (since the highlighting is done via an extension). You can probably force it to highlight via custom code in your extension.

```
// Highlight any translated field
$field->addExtraClass('LocalisedField');
```

**Comment by phptek** [comment]
@tractorcow thanks. However;  I just cleared my DB, re-added `FluentExtension` to `SiteTree` and to `Page` (and one or two others) then ran `dev/build`, but again, when looking at a standard "Page" object (which has "FluentExtension" applied to it via YML config) the CMS icon doesn't appear for fields apart from Title, Content and MenuTitle which are obviously applied directly to SiteTree objects, what am I doing wrong?

config.yml

    SiteTree:
      extensions:
        - FluentExtension
        - FluentMenuExtension
        - FluentFilteredExtension
    Page:
      extensions:
        - FluentExtension
        - FluentMenuExtension
        - FluentFilteredExtension

**Comment by tractorcow** [comment]
You should only add these extensions to the base dataclass; Adding it to `Page` should have no benefit.

Also take care that you are doubling up your custom extensions with the core ones; `FluentSiteTree` (which subclasses `FluentExtension`) is added to `SiteTree` in `fluent/_config/extensions.yml`, so you shouldn't really need to add it at all.

Can you show me the code which adds your custom fields? (your `Page::getCMSFields` or `Extension::updateCMSFields`).

**Comment by tractorcow** [comment]
> you need to make sure that extensions are called on those fields

What I mean is that you need to make sure that `$this->extend('updateCMSFields', $fields)` is called AFTER you add the fields to `$fields`, not that you should add the extensions via config. :D

**Comment by phptek** [comment]
@tractorcow I am an idiot. While I had added calls to `$this->extend('updateCMSFields', $fields);` that was _only_ on custom DataObjects (which works A-OK). I have now added it to pagetypes and voila.

...closing.

**Comment by tractorcow** [comment]
Ah you did it ;D good job!

Be careful with SiteTree::getCMSFields; You could end up calling extensions twice on your field list (once after scaffolding the basefields, and then again after adding custom fields). sometimes that's not a big issue, but it can often act weird with some extensions. Use beforeUpdateCMSFields whenever possible to prevent that.

Best of luck and glad I could help (and you're not an idiot you are wonderful bro) :package:
