### ISSUE TITLE
CMS Page Filter is broken

### ISSUE THREAD

**Issue by phptek** [tractorcow/silverstripe-fluent#124]
If I install Fluent in SS 3.1.12, I can no longer filter on PageTypes or perform a standard "Content" text search from within the CMS' "Filter" located in the centre pane. Instead, a complete list of _all_ page objects is returned as if I had instructed the CMS to build me the standard SiteTree. It isn't even a search-result that I can "clear".

I can try and futz the URL to include/exclude the "l" parameter to no avail e.g. 

`/?locale=en_NZ&q[FilterClass]=CMSSiteTreeFilter_Search&q[ClassName]=MyPageType`

or 

`/?locale=en_NZ&l=en_NZ&q[FilterClass]=CMSSiteTreeFilter_Search&q[ClassName]=MyPageType`

Removing the module, and it works again. By "Remove" I mean delete the "fluent" directory.

**Comment by tractorcow** [comment]
What other modules do you have installed? You don't have translatable or subsites do you?

You should be able to search by page type; You haven't translated the ClassName at all have you?

**Comment by phptek** [comment]
Hmmm this is a CWP project and it has _both_ (!!) is there something I need to be aware of with regard to this?

**Comment by phptek** [comment]
If `ClassName` is a bad choice for translation, should it not be added to the `field_exclude` array?

**Comment by tractorcow** [comment]
It sure should be, imo :D

**Comment by phptek** [comment]
Interesting...commenting out fluent.js in `FluentLeftAndMain::init()` "fixes" it

**Comment by phptek** [comment]
OK, the fix is as follows:

````javascript
		$('.cms-panel-deferred').entwine({
			/**
			 * Ensure that any deferred panel URLs include the locale parameter in their URL
			 */
			onadd: function() {
				var url = this.attr('data-url'),
					newUrl = urlForLocale(url, $.cookie('FluentLocale_CMS')),
                    // Ensure "incoming" data-url is properly filtered before being re-applied into the DOM
                    i18nNewUrl = ss.i18n.sprintf(this.attr('data-url'), newUrl);
				
                this.attr('data-url', i18nNewUrl);
				this._super();
			}
		});
````

...when I get time in the next day or two and have tested it a bit more, I'll issue a PR :-)

**Comment by phptek** [comment]
Grrr bloody NetBeans kept re-apply my PHP format rules. Have a look at that @tractorcow :-)
