### ISSUE TITLE
Homepage view breaks when locale is used

### ISSUE THREAD

**Issue by phptek** [tractorcow/silverstripe-fluent#125]
SS 3.1.2 / Fluent 3.2.1 (using aliases) / CWP 1.0.7 (w/Translateable) PHP 5.5.9

The Problem: 

- Navigating to the homepage (clicking or futzing the URL) results in 404
- Seems to be to do with `FluentRootURLController::handleRequest()` line 93

If I dump `$localeURL.'/'.RootURLController::get_homepage_link().'/'` which is passed as a param to `$request->setUrl()` I get: `en/en/home/` and the page results in a 404 with the debugging removed.

This seems to be because `RootURLController::get_homepage_link()` is taking account of "Translateable" and appending the extra aliased locale from (decorated) SiteTree::$current_locale which Fluent also utlises.

The fix for me is simply to add `SiteTree::remove_extension('Translatable')` to mysite/_config.php which I think should be "Recommended" in Configuration.md, as it's currently buried in translatable.md which I hadn't read because (and call me pedantic..) I wasn't actually "Migrating"...thoughts?

**Comment by tractorcow** [comment]
Honestly, I haven't tested this module alongside translatable. My feeling
is that these modules both try to do much the same thing, but in
fundamentally incompatible ways.

I have heard that users have had success with fluent and subsites, however.

Is there a fix we can apply to the root controller that adds the special
exemption for translatable, maybe?

You can also replace the root controller via injector if you want to
include logic custom to your project.

**Comment by phptek** [comment]
@tractorcow I'm not convinced replicating `RootURLController` via Injector  is particularly DRY, so how about something like the following in `FluentRootURLController`:

        /**
     * 
     * @param string $localeURL
     * @return string
     */
    public static function fluent_homepage_link($localeURL) {
        $link = parent::get_homepage_link();
        if(class_exists('Translatable')) {
            $locale = Fluent::get_request_locale();
            if(stristr($localeURL, $locale) !== false) {
                return $localeURL;
            }
        }
        
        return $link;
    }

....this would be called as follows on line 93:

    $request->setUrl(self::fluent_homepage_link($localeURL).'/');

...basic testing suggests it seems to work (Disabling Translatable seems to kill a CWP website :-(

**Comment by tractorcow** [comment]
> This seems to be because RootURLController::get_homepage_link() is taking account of "Translateable" and appending the extra aliased locale from (decorated) SiteTree::$current_locale which Fluent also utlises.

Can you please add a comment to this effect in the code of your pull request?
