### ISSUE TITLE
Native language string isn't always returned

### ISSUE THREAD

**Issue by phptek** [tractorcow/silverstripe-fluent#130]
Looking at `FluentExtension::LocaleInformation()`, for the `LanguageNative` value; In the event an ambiguous language is encountered such as Portugese which is spoken in two countries, then `false` is returned by the following out-of-the-box logic:

````php
i18n::get_language_name(i18n::get_lang_from_locale($locale), true)
````

The above makes use of `i18n::$common_languages` but is hamstrung by _not_ using a 2-char country code index for languages spoken in multiple countries (they use the full locale as keys). However there is `i18n::$common_locales` which _does_ have a "native" string we can utlise and _is_ keyed by the full locale.

Summary: FluentExtension::LocaleInformation() should have access to all native language translations available in the framework...fix incoming

**Comment by phptek** [comment]
N.b I haven't looked at the _entire_ differences between the languages contained in each array, so a bit of self one-upmanship might be (if required) to merge and filter the two arrays for our own purposes, such that we only have the one source.

Thoughts??

**Comment by tractorcow** [comment]
Fixed with https://github.com/tractorcow/silverstripe-fluent/pull/131
