### ISSUE TITLE
Default translated field value doesn't seem logical

### ISSUE THREAD

**Issue by phptek** [tractorcow/silverstripe-fluent#132]
## The Problem:

First-time page-edits, post module install using the non-default locale in the CMS, will render the non-localised field's value as per the value of selected locale's field-value.

## Reproduction

Assuming a default locale of `en_NZ` and some other locale is configured e.g. `ar_EG` (Arabic, Egypt):

* Login to the CMS
* Navigate to any page in the CMS
* Observe that page's "Title" reads in English (Probably)
* Perform a DB query on the SiteTree table for the "Title", "Title_en_NZ", "Title_ar_EG" fields
* Observe that by default, "Title" contains an English string, "Title_en_NZ" is NULL, "Title_ar_EG" is NULL
* In the CMS select "Arabic (Egypt)" from the CMS' locale selector
* Enter an "Arabic" title
* Press "Save"
* Observe the Title field in the CMS now reads in Arabic
* Run the same SQL query as above
* Observe that the "Title" column contains Arabic, "Title_en_NZ" is still NULL, and "Title_ar_EG" is in Arabic
* Observe in the frontend in "Stage" mode, that that page's title is also in Arabic, regardless of any frontend language selection made
* In the CMS select "English (New Zealand)" from the CMS' locale selector
* Observe that the visible title is in Arabic

## Summary

If I had selected "Save and Publish" instead of just "Save" then that page's title would also be in Arabic, and that change would be live.

...this doesn't seem to be logical behaviour to me. Perhaps I'm coming at things from an odd angle, but I'd expect the YML-configured `default_locale` version of the field to be pre-populated with whatever is already in the "Title" field (or make this behaviour configurable) and for the un-translated field to be left-alone for subsequent updates.

Possibly I might even expect that any query augmentation totally ignores the un-translated fields while `Fluent` is installed. But I'm not sure of the wider impact of this sort of thinking.

Might this be related to a response in #128 regarding an inherent difficulty in creating fields with the values of other, pre-existing fields?

**Comment by tractorcow** [comment]
Hm, this could be fixed by ensuring that the default locale field (`Title_en_NZ`) is always given a value on initial write. The default is ment to be the master, so if it's missing the module develops severe paranoia and throws in the first value it can see (in this case, your arabic value).

We can fix this by ensuring that when loading a record from the database, if the Title_en_NZ field is empty, it should be populated by the value in Title (rather than being left blank), which ensures this value is written back to the DB rather than the new non-default value.

**Comment by tractorcow** [comment]
Yes this seems complicated... but that code was the hardest part to write so I understand how frustrating this is. :)

**Comment by phptek** [comment]
So in order to avoid a Developer race condition, who'se going to have a stab at patching this? If that's me, some pointers as to where you recommend starting would be super-helpful, otherwise I'll poke around until I find a suitable scab to pick.

**Comment by tractorcow** [comment]
At the moment I'm working on helping fix up https://github.com/tractorcow/silverstripe-fluent/pull/120. I'll see if I can fix this as a part of that.

**Comment by tractorcow** [comment]
Ok, I just thought of an easy win for this issue.

In `onBeforeWrite`, if we know that we are writing a new record, and we aren't writing in the default locale, then copy the value of `$field` to `$field_$defaultLocale`.

Unit test for this is to set the locale to the non-default, write a new record, then write a second time to a different value. Then change to the default locale, re-select that record from the database, and make sure the field value is the original value.

**Comment by tractorcow** [comment]
Also I need to fix travis on this repo. sorry. :D

**Comment by phptek** [comment]
This is proving tricky. The manipulation out of `FluentExtension::augmentWrite()` contains the expected data for the default (non localised) field. This renders any solution based on `onBeforeWrite()` moot given the former is called after the latter in `DataObject::write()`....

**Comment by phptek** [comment]
Ramblings on this to-date:

**Comment by tractorcow** [comment]
We can't remove the field_default, because when the record is loaded into memory the "current" locale value is saved into the base field, so that once it's written back to the DB we need to swap the base field with the default locale field again, as well as writing the current value of the base field to the specific locale field (I hope that made sense because I understand it's confusing).

Without this behaviour it's not possible to determine what the default locale value is if you are viewing in a non-default locale.

**Comment by phptek** [comment]
> as well as writing the current value of the base field to the specific locale field
..and it's this that is proving tricky. `onBeforeWrite()` is called 4 times (The no. non-abstract ancestors the current DataExtension has with a method of `onBeforeWrite()` on it) this means even just testing and hard coding `$this->owner->setField('Title', 'Wibble')` results in _both_ the "Title" and "Title_ar_EG" being "wibble".

I'm trying to sort this out now, but..well..

**Comment by phptek** [comment]
@tractorcow I've been looking at this for about a day now which feels way too long as though I'm looking in the wring place. How are you going with patching #120 - anything promising there?

**Comment by tractorcow** [comment]
I've been too busy to work on Fluent today I'm afraid. =(

Maybe by the end of the week I might be able to come up with a fix for the created-in-non-default-locale issue.

**Comment by phptek** [comment]
Totally cool and looking forward to seeing how this eventually turns out :-)

**Comment by tractorcow** [comment]
I also think it's worth solving this issue without trying to fit it into #120 at this stage; Probably better to get this out as soon as possible.

**Comment by tractorcow** [comment]
Fixed with #136
