### ISSUE TITLE
Default translated field oddities

### ISSUE THREAD

**Issue by phptek** [tractorcow/silverstripe-fluent#138]
@tractorcow This issue relates to #132 with related bug(s). I have not verified if the following were introduced recently or existed prior to #132 being fixed:

## Env

* Fluent: dev-master as 3.2.2 with aliases enabled in YML for all locales and FluentExtension + FluentFilteredExtension enabled for SiteTree
* Newly updated, raw SS 3.1.12 (No project-code whatsoever)
* PHP 5.5 / Ubuntu 14.04
* Chrome 44 (CMS) Firefox 39 (Frontend)

## Bug reproduction

* [OK] Login to the CMS
* [OK] Select "English (New Zealand)" from LHS locale menu
* [OK] Create new top-level "Page"
* [OK] Enter a title in English; e.g. "TEST 01"
* [OK] Press "Save & Publish"
* [OK] Observe "Page name" field reads "TEST 01" and "Navigation label" reads" "TEST 01"
* [OK] Navigate to /en/test in the frontend, observe Menu title reads "TEST 01" and page-heading reads "TEST 01"
* [OK] Select "Arabic (Egypt)" from LHS locale menu
* [FAIL] Observe "Page name" suddenly displays "New Page" (Could be session related as this seems inconsistent..)
* [OK] Enter a "Page name" in Arabic; e.g. "TEST 01 Arabic"
* [FAIL] Focusing off the "Page name" field does _not_ auto-change the "Navigation label" field as it would normally do (No JS errors observed) - this could be related to the above as it also seems inconsistent)
* [OK] Press "Save & Publish"
* [FAIL] Observe "Page name" field reads "TEST 01" (Expected "TEST 01 Arabic")
* [FAIL] Navigate to /en/test in the frontend, observe Menu title reads "TEST 01 Arabic" and page-heading reads "TEST 01" (Expected both to read "TEST 01")
* [FAIL] Navigate to /ar/test in the frontend, observe Menu title reads "TEST 01 Arabic" and Page-heading reads "TEST 01" (Expected both to read "TEST 01 Arabic")

Relating to #132 I see similar behaviour for _pre-existing_ pages:

* [OK] Login to the CMS
* [OK] Select "English (New Zealand)" from LHS locale menu
* [OK] Open an existing default page e.g "About us" (ID #2)
* [OK] Select "Arabic (Egypt)" from LHS locale menu
* [OK] Enter a new "Page name" in Arabic; e.g. "About us in Arabic"
* [OK] Press "Save & Publish"
* [FAIL] Observe the "Page name" fiel din thre CMS reads "About us" but the "Nvaigatioin field" reads "About us in Arabic"
* [FAIL] Navigate to /en/about-us in the frontend, observe Menu title reads "About us in Arabic" and page-heading reads "About us" (Expected both to read "About us")
* [FAIL] Navigate to /ar/about-us in the frontend, observe Menu title reads "About us in Arabic" and page-heading reads "About us" (Expected both to read "About us in Arabic")

**Comment by tractorcow** [comment]
Can you please provide your config.yml for the fluent locales?

**Comment by tractorcow** [comment]
> [FAIL] Observe "Page name" suddenly displays "New Page" (Could be session related as this seems inconsistent..)


If you create a page in a non-default locale, only the first value written to that field will be set as the default, up until you re-save this in the default locale with a defined value.

If English (NZ) is not the default locale then I would expect this behaviour.

**Comment by phptek** [comment]
````yml

---
Name: myfluentconfig
After: '#fluentconfig'
---
Fluent:
  restrict_native_lang: true
  locales:
    # English (New Zealand)
    - en_NZ
    # Egyptian Arabic
    - ar_EG
    # Chinese (Simplified)
    - zh_CN
    # Chinese (Traditional)
    - zh_TW
    # Dutch
    - nl_NL
    # French
    - fr_FR
    # German
    - de_DE
    # Indonesian (Assume Bahasa)
    - id_ID
    # Italian
    - it_IT
    # Japanese
    - ja_JP
    # Korean
    - ko_KR
    # Polish
    - pl_PL
    # Portugese (Brazil)
    - pt_BR
    # Russian
    - ru_RU
    # Spanish
    - es_ES
    # Turkish
    - tr_TR
    # Vietnamese
    - vi_VN
  aliases:
    # Set aliases for each locale url as necessary
    en_NZ: en
    ar_EG: ar
    zh_CN: cn
    zh_TW: tw
    nl_NL: nl
    fr_FR: fr
    de_DE: de
    id_ID: id
    it_IT: it
    ja_JP: jp
    ko_KR: ko
    pl_PL: pl
    pt_BR: pt
    ru_RU: ru
    es_ES: es
    tr_TR: tr
    vi_VN: vn
  field_include:
    # Page, NewsPage, EventPage
    - Title
    - Content
    - Abstract
    - Location
  # Determine if the site should detect the browser locale for new users.
  # Turn this off to disable 302 redirects on the home page
  detect_locale: false
  # Forces the module to act in domain mode
  force_domain: false
  # Fluent module's locale signal in controllers (inc CMS)
  query_param: content_locale
---
Name: myfluenti18nconfig
After: '#fluenti18nconfig'
---
i18n:
  default_locale: en_NZ

**Comment by tractorcow** [comment]
Did you not specify a default_locale for fluent? This will (without a doubt) cause issues.

```
Fluent:
  default_locale: en_NZ
```

Setting this on i18n isn't enough. I need to make it an error if this is not assigned.

**Comment by phptek** [comment]
No, because it's already set in `fluent/_config/fluent.yml`. If, just for testing purposes I edit `default_locale` in `fluent/_config/fluent.yml` to `es_ES`, then run dev/build, I can verify that the following debug output in my `Page` constructor gives me `es_ES`:

````php
        var_dump(Fluent::config()->default_locale);
        die;

Is this not expected?

**Comment by phptek** [comment]
And regardless, yeah throwing an exception as opposed to a user_error would be more appropriate I think as it's basically a "Fatal" error, when things can go seriously awry without it. But then again, what's the point of setting it in the module's fluent.yml by default then?

**Comment by tractorcow** [comment]
Absolutely, you're right. I'll test it out now. ;D

**Comment by phptek** [comment]
Sweetas!

**Comment by phptek** [comment]
Seriously though, as awesome as I can see this module is (and it _is_), I fundamentally don't understand how other's are managing to use it successfully without heavily working around this particular issue - perhaps by advising clients to "do this" and "not do that", except on Sunday's at about Teatime when you should "do that" instead! ;-)

**Comment by tractorcow** [comment]
```
[OK] Login to the CMS
[OK] Select "English (New Zealand)" from LHS locale menu
[OK] Create new top-level "Page"
[OK] Enter a title in English; e.g. "TEST 01"
[OK] Press "Save & Publish"
[OK] Observe "Page name" field reads "TEST 01" and "Navigation label" reads" "TEST 01"
[OK] Navigate to /en/test in the frontend, observe Menu title reads "TEST 01" and page-heading reads "TEST 01"
[OK] Select "Arabic (Egypt)" from LHS locale menu
[FAIL] Observe "Page name" suddenly displays "New Page" (Could be session related as this seems inconsistent..)
[OK] Enter a "Page name" in Arabic; e.g. "TEST 01 Arabic"
[FAIL] Focusing off the "Page name" field does not auto-change the "Navigation label" field as it would normally do (No JS errors observed) - this could be related to the above as it also seems inconsistent)
[OK] Press "Save & Publish"
[FAIL] Observe "Page name" field reads "TEST 01" (Expected "TEST 01 Arabic")
[FAIL] Navigate to /en/test in the frontend, observe Menu title reads "TEST 01 Arabic" and page-heading reads "TEST 01" (Expected both to read "TEST 01")
[FAIL] Navigate to /ar/test in the frontend, observe Menu title reads "TEST 01 Arabic" and Page-heading reads "TEST 01" (Expected both to read "TEST 01 Arabic")
```

I have followed this and I can't reproduce the errors you've given. (with your exact config).

I'll try again with a few more combinations. :D

**Comment by tractorcow** [comment]
Aha, I found a bug in saving a record in a non-default locale. I'll update soon.

**Comment by phptek** [comment]
Also, as you're probably aware `testPublish()` has been failing for a while. Not sure if that's relevant and whether it should pass once you patch this?

**Comment by tractorcow** [comment]
The bug I noticed is in the CMSMain::publish method; Or at least triggered by.

**Comment by tractorcow** [comment]
It looks like, when doing a write, sometimes the translated fields in $manipulation are wrong, but the value in $this->owner->FieldName is right.

Possible solution is to change augmentWrite to distrust the set values in augmentWrite in favour of the values in $this->owner.

I suggest for now that you use an older version of this module; Can you set to 3.2.1 for now and I'll get back to you once I've resolved this. 3.2.2 should be distrusted.

**Comment by phptek** [comment]
Sure, I'll give it a go but if memory serves the original bug that illustrates the base problem (#132) was discovered in 3.2.1, but I'll give it a shot and let you know how I go. :-)

**Comment by tractorcow** [comment]
Ok I've found something amazing.

If you have the FluentExtension added TWICE to a dataobject it breaks everything in a really bad way.

**Comment by phptek** [comment]
OK, in an unadulterated SS 3.1.x-dev with Fluent at `5856da` (dev-master) with only one `FluentExtension` (Defined as a module default) seems to be much better.

There is still a related issue, that could be worked around with good user-instruction but always good to assume the worst of a user to ensure the best experience :-P

[OK] Login to CMS
[OK] In CMS Select "English (New Zealand)" locale
[OK] Create new page with title "TEST 01"
[OK] Observe navigation label changes to "TEST 01"
[OK] Observe URL Segment changes to /en/test-01
[OK] Save & Publish
[OK] View in the frontend: as /en/test-01
[OK] Observe Menu title reads "Test 01"
[OK] Observe Page title reads "TEST 01"
[OK] Observe URL segment reads "/en/test-01"
[OK] In CMS Select "Chinese (Taiwan)" locale
[OK] Modify page title to read "TEST 01 Something in Taiwanese"
[FAIL] Observe navigation label changes to "TEST 01 Something in Taiwanese"
[OK] Observe URL Segment is still /en/test-01
[OK] Save & Publish
[OK] View in the frontend: as /en/test-01
[FAIL] Observe Menu title still reads "Test 01" (It reads "TEST 01 Something in Taiwanese")
[OK] Observe Page title reads "TEST 01"
[OK] Observe URL segment reads "/en/test-01"
[OK] View in the frontend: as /tw/test-01
[FAIL] Observe Menu title still reads "Test 01" (It reads "TEST 01 Something in Taiwanese")
[OK] Observe Page title reads "TEST 01 Something in Taiwanese"
[OK] Observe URL segment reads "/en/test-01"
[OK] In CMS Re-select "English (New Zealand)" locale
[OK] Change the Menu Title back to "TEST 01"
[OK] Save & Publish
[OK] View in the frontend: as /en/test-01
[OK] Observe Menu title reads "Test 01"
[OK] View in the frontend: as /tw/test-01
[OK] Observe Menu title still reads "Test 01"

Summary: Without thinking _long_ and hard about it, my gut feel is that the CMS' default behaviour for auto-changing the MenuTitle is correct, but that this should only happen on page-creation. So whatever the default locale is, and whatever the currently selected locale is, the first MenuTitle is the one that's used with _no further_ auto-updates of that field. While still allowing manual changes to that field.

This is obviousely further complicated by the `FluentMenuExtension`...my brain hurts. Thoughts??

**Comment by tractorcow** [comment]
Yeah, navigation label is a really annoying oddity. It's probably because it saves a blank record if it matches the title, and that messes with fluent's detection of translations.

Any blank field means "just use the default", which in this case is not going to be correct. We could add a hack to FluentSiteTree to force it to always be written to the database if Title is set, maybe.

**Comment by phptek** [comment]
Just quickly hacking a CMSMain.EditForm.js version of `updateRelatedFields()` into `fluent.js` I can prevent the CMS' default behaviour for only fluent-enabled fields. This may suit my own scenario, but the question is does it suit everyone else's? I wanted to find a data-attribute that gave me "Is New" or "Is Modified" (etc) so this logic could be further narrowed down to default CMS behaviour when the page is newly created, but as soon as it was saved, only _manual_ edits would be able to change the MenuTitle field.

I fear this is too obtrusive into how the CMS does things out of the box though...

````javascript
		/**
         * 
		 * Warning: overrides CMSMain.EditForm::updateRelatedFields() for Fluent
         * module specific functionality.
		 */
		$('.cms-edit-form .LocalisedField input[name=Title]').entwine({
			
			/**
			 * Function: updateRelatedFields
			 * 
			 * Update the related fields if appropriate
			 * (String) title The new title
			 * (String) origTitle The original title
			 */
			updateRelatedFields: function(title, origTitle) {
				// Update these fields only if their value was originally the same as the title
				this.parents('form').find('input[name=MetaTitle], input[name=MenuTitle]').each(function() {
					var $this = $(this);
                    $this.val(origTitle);
                    // Onchange bubbling didn't work in IE8, so .trigger('change') couldn't be used
                    if($this.updatedRelatedFields) $this.updatedRelatedFields();
				});
			}
        });

**Comment by tractorcow** [comment]
We could do an onBeforeWrite in FluentSiteTree like

```php

public function onBeforeWrite() {
    $menuTitle = $this->owner->getField('MenuTitle');
    if(empty($menuTitle)) {
        $this->owner->setField('MenuTitle', $this->owner->Title);
    }
}
```

**Comment by phptek** [comment]
Testing....

**Comment by phptek** [comment]
That didn't work, this does - to a point (Still testing)

````php
        if(empty($menuTitle) || $menuTitle === 'New Page') {
            $this->owner->setField('MenuTitle',  $this->owner->Title);
        }

...can't seem to find the lang file where "New Page" is defined yet..

**Comment by phptek** [comment]
AFAIKT we just hard-out need to ensure the default_locale's "Title" value is _always_ reflected in the MenuTitle field, regardless.

This would indicate we need this logic: 
````php 
$this->owner->setField('MenuTitle',  $this->owner->Title); 
````

..but it doesn't get away from the fact that the CMS is always going to auto-update the MenuTitle field with that JS snippet above taken from `CMSMain.EditForm.js`.

**Comment by tractorcow** [comment]
Unless they are different, of course :P

**Comment by tractorcow** [comment]
That `new page` thing has caused me drama. I once had a page called `New Zealand : Something` and apparently the script only looks at the first three characters, and decided to rename it to the page title.

From memory it was in javascript, not in the PHP.

**Comment by phptek** [comment]
>Unless they are different, of course :P

Yes. It's _really_ hard balancing what's good for a module / common logic and APIs with what seems sensible for a specific client. In my case - and fortunately - the MenuTitle should not be altered, so the JS hack I've implemented works.

If you come up with something cleaner, just update the ticket and thanks for jumping onto everything I've been submitting recently so quickly :-)

**Comment by phptek** [comment]
I have a little better understanding of what's going wrong here: In a new install of SS 3.1.3 _with_ Fluent, the localised default_locale field versions, receive the original, non-localised field's value. If, as I am doing, you retrospectively install Fluent, this does not happen and it is for this scenario, I am attempting to patch.

So far this works saving to `SiteTree` but `SiteTree_Live` still exhibits the "broken" behaviour.

**Comment by phptek** [comment]
Fixed. See thread in #141
