### ISSUE TITLE
Enhancement: API to determine if current page has translated content

### ISSUE THREAD

**Issue by phptek** [tractorcow/silverstripe-fluent#142]
We've discussed this issue before, but I'm adding it here for a central discussion point, should anyone want to join in.

It would be very useful to have a public method e.g. `isTranslated()` on `FluentSiteTree` that returns a locale or an empty string (for a consistent API, none of this `@return mixed` business..) depending upon whether the current page has _any_ translated content.

This would be useful for example in restricting the no. locales shown in the front-end's locale selector to locales for which the current page has translated content. Or to redirect users who force a URL or mistakenly arrive at a URL of a locale that isn't translated. 

(N.b. both of the above happen to be client requirements in my current project!).

By "Translated content" I mean:

 1. At least _one_ of a page's translated fields e.g. `Title_ar_EG` is populated, _And/Or_
 2. At least _one_ of a page's `has|many_xxx` relations, itself has at least one translated + populated field, _And/Or_
 3. At least _one_ of a page's arbitrary ORM calls to a DataObject sub-class itself has at least _one_ translated & populated field 

If I get time, I'll write some failing tests that illustrate how this might work.

**Comment by phptek** [comment]
...maybe a better name would be `isTranslatedInto($locale)` which returns a boolean?

**Comment by tractorcow** [comment]
This would be very easy to do in user code.

```php
public function isTranslated($locale) {
    $field = Fluent::field_for_locale('Content',$locale);
    return !empty($this->$field);
}
```

Unfortunately there's no distinction between "empty in this locale" and "untranslated".

**Comment by phptek** [comment]
Sure, I know this :-) but would only work for "native" fields on the current object's class, defined in the `$db` static (and `$has_xxx` also?).

The kicker AFAIKT is with arbitrary calls to `DataObject::get("Foo")` within that page object, hence my messing about with `augmentSQL` just to get at that "meta" data. This is so that the current page knows that there are calls for `getMyAwesomeNews()` which calls `DataObject::get('NewsPage')` (for example) and for each such call, that their is translated data.

Current thinking is around extending `ClassInfo` and using something like `ReflectionClass::export($this->owner->class);` and inspecting the output, to get a unique array of classes being called via the ORM in the current page's class.

**Comment by phptek** [comment]
OK, there can't possibly be any way to do this in the module, let alone in framework. It takes some crazy reflection to achieve what I want. I've come at this problem from another angle which is to have my custom ORM calls update a class-property with the populated and locale-enabled field data, that they know about:

* __What it does:__ Updates a class-property with all populated locale-fields of a dataClass, for each ORM call
* __How it's implemented:__ The method is pasted into existing `<MyClass::get>` calls

Now I can leverage what's available from `$this->getORMTranslations()` anywhere it's needed.

### Page.php

````php
    public function getMyNews() {
        $news = DataObject::get('NewsPage', "\"ShowOnHomePage\" = '1'");
        
        // Are there translations we should know about?
        $this->updateKnownTranslations($news);

        return $news;
    }
````

### MyPageExtension.php

````php
	/**
	 * 
	 * @param DataList $list
	 */
	public function updateKnownTranslations(DataList $list) {
		$dataClass = $list->dataclass();
		$baseClass = ClassInfo::baseDataClass($dataClass);
		$locale = Fluent::current_locale();
		$locales = Fluent::locales();
		$usedLocales = array();
		if($fluentFields = array_keys(FluentExtension::translated_fields_for($baseClass))) {
			foreach($fluentFields as $field) {
				foreach($locales as $locale) {
					$fluentField = Fluent::db_field_for_locale($field, $locale);
					$filtered = $list->filterByCallback(function($item) use($fluentField, $locale, &$usedLocales) {
						if(!empty($item->getField($fluentField))) {
							$usedLocales[] = $locale;
						}
					});
				}
			}
			
			if($usedLocales) {
				$this->setOrmTranslations(array($dataClass => $usedLocales));
			}
		}
	}
	
	/**
	 * 
	 * Determine if translations exist on the fields of classes called in arbitrary 
	 * ORM queries made in the current object. $this->_ormTranslations is populated
	 * "manually" by interjecting with every (most) custom ORM call(s) in the project.
	 * 
	 * @param boolean $justLocales 
	 * @return array
	 */
	private function getORMTranslations($class, $justLocales = true) {
		if($this->_ormTranslations && isset($this->_ormTranslations[$class])) {
			return $this->_ormTranslations[$class];
		}

		$return = array();
		if($justLocales) {
			foreach($this->_ormTranslations as $class => $locales) {
				foreach($locales as $locale) {
					$return[] = $locale;
				}
			}
		} else {
			$return = $this->_ormTranslations;
		}
		
		return $return;
	}
	
	/**
	 * 
	 * @param array $array
	 */
	public function setOrmTranslations($array) {
		$this->_ormTranslations = $array;
	}
````
