### ISSUE TITLE
Portuguese not output on frontend

### ISSUE THREAD

**Issue by Sanderha** [tractorcow/silverstripe-fluent#143]
I added pt_PT (portugal) in my config file, and everything works fine as usual. The problem is, that "portuguese" is not being output on the frontend, by the $LanguageNative variable. I had to do a custom If statements, manually outputting it. 
This problem does not occur with any other language I tried.

Is it a bug?

**Comment by tractorcow** [comment]
Hm, it should output perfectly fine.

Can you please attach your YML config for me? The language name comes from i18n::$common_locales which has an entry for pt_PT and should appear as `português (Portugal)`

**Comment by Sanderha** [comment]
Hey sorry for the late response.
Here is my YML config, unfortunately Github wouldnt let me just attach the file.

```lang
---
Name: myfluentconfig
After: '#fluentconfig'
---
Fluent:
  default_locale: da_DK
  locales:
    - da_DK
    - en_US
    - de_DE
    - fr_FR
    - cs_CZ
    - pl_PL
    - ru_RU
    - sk_SK
    - pt_PT
    - es_ES
  aliases:
    da_DK: da
    en_US: en
    de_DE: de
    fr_FR: fr
    cs_CZ: cs
    pl_PL: pl
    ru_RU: ru
    sk_SK: sk
    pt_PT: pt
    es_ES: es
  domains: []
    #  www.example.com.au:
    #    locales:
    #      - en_AU
    #      - en_US
    #    default_locale: en_AU
    #  www.example.co.nz:
    #    locales:
    #      - en_NZ
  detect_locale: false
  remember_locale: false
---
Name: myfluenti18nconfig
After: '#fluenti18nconfig'
---
i18n:
  default_locale: da_DK
```
