### ISSUE TITLE
Running into "Row size too large" MySQL issue

### ISSUE THREAD

**Issue by micschk** [tractorcow/silverstripe-fluent#145]
I have a page with 24 varchar fields and 24 htmltext fields, which seems to hit a Mysql/innoDB limit(?):

```
Row size too large (> 8126). Changing some columns to TEXT or BLOB or using ROW_FORMAT=DYNAMIC or ROW_FORMAT=COMPRESSED may help. In current row format, BLOB prefix of 768 bytes is stored inline.
IN POST /site/admin/pages/edit/EditForm
Line 598 in /home/site/framework/model/MySQLDatabase.php
```

I'd agree that 24 fields on one page could probably be considered an edge case, and I think this may be a byproduct of saving languages in the same row. With this issue report, I'm hoping that someone may be able to explain this issue a bit more/see if this is something that can be fixed.

If this indeed cannot be fixed, a suggestion would be to add a section to the docs, warning devs and explaining this limitation.

**Comment by tractorcow** [comment]
Yep, you need to drop some locales or localise fewer fields. :) There's very little that can be done from fluent's point of view, I'm afraid.

Have you tried postgres?

You could also try splitting your class into multiple tables.

```php

class MyPageBase extends Page {
	private static $db = // 12 fields
}

class MyPage extends MyPageBase {
	private static $db = // other 12 fields
}
```

**Comment by wernerkrauss** [comment]
You could split out some fields to a  `$has_one` /  `$belongs_to` relation  and use https://packagist.org/packages/stevie-mayhew/hasoneedit to get the fields again in backend. 

Though you'd need some other magic or call the outsourced fields through $this->HasOneRelationName ...

**Comment by tractorcow** [comment]
Yeah that could work as well :) It possibly would break lots of other modules though.

**Comment by wernerkrauss** [comment]
Of course you can only use this for your own model you can completely control. And only put "unimportant" data in it, you don't have to access from other modules directly.

**Comment by phptek** [comment]
@micschk Have a lok at #174 some of which may help you :-)

**Comment by tractorcow** [comment]
I'm considering documenting this as a limitation of this module, rather than a bug per-se. If I document this, and include these work-arounds in the documentation, would that be sufficient to close this?

**Comment by phptek** [comment]
@tractorcow My personal view is yes, so long as it was made fairly salient in the README and included MySQL / MariaDB versions affected etc.

**Comment by wernerkrauss** [comment]
You might try this in your DataObject that causes  the"Row size too large" error:

private static $create_table_options = array(
		'MySQLDatabase' => 'ENGINE=InnoDB ROW_FORMAT=COMPRESSED'
);

Alternatively DB creations also calls `augmentDatabase()` where you could alter the table to use compressed row format.

**Comment by phptek** [comment]
@wernerkrauss good find re: compressed format. Could you possibly at it to the closed item at #174 for when people are googling thids issue. That would make it the go-to spot for solutions to this problem :-) or maybe one for @tractorcow (or any one of us) to add it into the README or at to the docs?

**Comment by lerni** [comment]
just thought https://github.com/Internetrix/silverstripe-fluent-extra-table should be mentioned here.

**Comment by micschk** [comment]
That looks great! 
I'd been thinking Fluent has the best interface, Translatable the best database structure, wouldn't it be great if we could somehow merge them... Fluent-extra-table to the rescue! :)

**Comment by wernerkrauss** [comment]
What influence does an extra table have on performance?

 

IMHO fluent is great if you don’t need total flexibility (user permissions or different sitetree per locale). 

 

Extra table sounds like a good extension to fluent but should be an option. A converting task if you have to switch later on would be great.

**Comment by micschk** [comment]
@wernerkrauss, my remark was on @lerni's link/module (if there was any confusion). This would be optional as-is, actually a (beefy) separate module. 

I'd be curious about performance as well (especially because the extra table seems to require quite some extra code). Though I'd expect no noticeable implications for most sites since we're usually caching anyway.

**Comment by robbieaverill** [comment]
We won't be fixing this in Fluent for SilverStripe 3, but have mitigated the problem somewhat by switching Fluent for SilverStripe 4 from horizontal scaling to vertical scaling (to some extent).
