### ISSUE TITLE
Silverstripe 3.2: language switcher doesn't collapse nicely

### ISSUE THREAD

**Issue by wernerkrauss** [tractorcow/silverstripe-fluent#157]
In SS 3.2 we seem to have a collapsed left menu more often (or some style has changed?), but the lang switcher still shows some stub of the currently selected language, see screenshot.

![screenshot-fluent-collapsed](https://cloud.githubusercontent.com/assets/1043925/10753250/f81629a2-7c8f-11e5-92d9-30fc5ba9ec70.jpg)

**Comment by tractorcow** [comment]
Ouch, I better fix that when I upgrade for 3.2. :)

**Comment by wernerkrauss** [comment]
Did a quick and dirty css fix for this:
```
/* fix a bug with fluent in 3.2 */
.cms-menu.collapsed .cms-fluent-selector .text {
    display: none;
}
.cms-menu.collapsed .cms-fluent-selector .cms-fluent-selector-locales {
    left: 0;
    right: auto;
}
```
though the selector is partially hidden by overflow of the whole panel. Would be better, if the selector would be able to  "pop out" like the other menu items below.

**Comment by tractorcow** [comment]
Thanks for the hack; I'll see if I can put it into an official fix.

**Comment by dhensby** [comment]
Fixed?

**Comment by tractorcow** [comment]
Fixed with https://github.com/tractorcow/silverstripe-fluent/pull/178
