### ISSUE TITLE
SS3.2: Bug in Locale menu

### ISSUE THREAD

**Issue by wernerkrauss** [tractorcow/silverstripe-fluent#158]
Fatal error: Call to a member function Link() on a non-object in /vagrant/www/fluent/code/extensions/FluentExtension.php on line 320

Somehow

DataObject::get($class)->byID($id)->Link();

crashes, when re-publishing the page it works. Dunno why.

when debugging i see that

Page::get()->byID(3) => null
Page::get()->filter('ID', 3) => DataList....

Maybe related to https://github.com/silverstripe/silverstripe-framework/issues/4700  and hopefully resolved in 3.2.1 ?

**Comment by tractorcow** [comment]
Ah, maybe. In which case, have you tested it with 3.2 dev branch?

**Comment by wernerkrauss** [comment]
not yet, just with the 3.2.0 release

**Comment by tractorcow** [comment]
I think it is possibly fixed.

I recently added full tests for 3.2 branch recently so it should be working.

**Comment by dhensby** [comment]
Fixed?

**Comment by tractorcow** [comment]
No idea... maybe @wernerkrauss could confirm?
