### ISSUE TITLE
Partial caching with t strings

### ISSUE THREAD

**Issue by Sanderha** [tractorcow/silverstripe-fluent#160]
Hello

If I have t strings (<%t Buttons.SeeDetails 'See details' %>) in a partial cached block of markup and switch the language, the t strings dont get updated.

Any ideas on how to make that happen? Or how to get partial cached content to update on language change?

**Comment by wernerkrauss** [comment]
did you flush after you updated the locale in your /lang/xy.yml file?
Are the strings updated outside the cached block?
I encountered strange problems with umlauts in language files and wrong file encoding, then the yml parser ignored the whole module's lang files...

Though this issue doesn't seem to be fluent related...

**Comment by Sanderha** [comment]
Yes I did flush and the strings are updated outside the cached block. 
This issue might indeed not be Fluent related, but I figured I'd give it a shot

**Comment by wernerkrauss** [comment]
So you need to invalidate the cached block using a better cache key? See https://docs.silverstripe.org/en/3.1/developer_guides/performance/partial_caching/

PS: you might also close this issue or move this discussion to another place like forum, IRC, or stackoverflow.

**Comment by Sanderha** [comment]
Alright, thanks a lot!

**Comment by wernerkrauss** [comment]
For completeness: It's also mentioned in the fluent docs: https://github.com/tractorcow/silverstripe-fluent/blob/master/docs/en/templating.md

**Comment by Sanderha** [comment]
Ah I see. Sorry for the inconvenience!

**Comment by tractorcow** [comment]
It's all good. :) I don't remember writing those docs!
