### ISSUE TITLE
Feature: Resolution for "Row size too large" MySQL issue

### ISSUE THREAD

**Issue by phptek** [tractorcow/silverstripe-fluent#174]
With reference to #145

@tractorcow I have just come across the problem ref'd in #145 too. We have 359 columns! (10 locales) on one PageType. Removing a handful from the `$translations` static, and running `dev/build` "solves" the problem.

The problem seems to occur on MySQL ~5.7 (A colleague's Docker setup uses 5.7 whereas I use 5.5 and I do not see the problem). I'm not sure when this constraint was introduced - it kinda seems like it's always been there, but again, I'm running 5.5 and I do not see the issue.

MySQL has a row size limit of 64Kb But BLOB and TEXT types do not count towards this limit.

From mysql.com

>"There is a hard limit of 4096 columns per table, but the effective maximum may be less for a given table. The exact limit depends on several interacting factors. "
>"Every table (regardless of storage engine) has a maximum row size of 65,535 bytes. Storage engines may place additional constraints on this limit, reducing the effective maximum row size. "

Additional info: http://stackoverflow.com/questions/24275959/what-is-the-max-number-of-columns-per-table-for-mariadb

Question: What do you think of an alternative, perhaps left-of-field solution that I had; Adapt Fluent so it can be put into "structured" (or just a non-default) mode, then make use of some "structured content" e.g. JSON data, who's keys are named for the field to be translated taken from the 
DataObject's `$db` static, and suffixed with "_EN", "_CN" (etc).

I've been meaning to write a `JSONText` type for some time as this solution lends itself well to some other interesting problems I come across sometimes. I've started work on a Structured Text module. N.b. a). It only partially works, b). As a result its not even alpha.

I'm only sharing it now to get feedback on the likelyhood of this module (or something like it) being useful for this bug.

**Comment by tractorcow** [comment]
I've thought about this, but we would have to disable a bunch of features, such as translated conditions (conditions only check the "default" locale).

Also, you would need to solve the issue of how to rewrite a SQLQuery so that the result would eventually extract the json column data. I can't see a mysql compatible solution, unfortunately. Postgres has native JSON columns, but if you're using postgres you wouldn't be having these issues in the first place. ;)

If you think this is an acceptable loss of functionality, then it could possibly be done.

There still remains the additional workaround of using additional tables.

```php
class ObjectA extends ObjectB {
	private static $db = array(); // first half of your translated fields
}
class ObjectB extends DataObject {
	private static $db = array(); // other half of your translated fields
}
```

**Comment by phptek** [comment]
So I can see how the splitting-up classes method _should_ work, but SS leaves pre-existing columns hanging-around, even if they're removed from the `$db` static (ether directly or by means of removing values from he `$translate` static).

So if like me, you've already got "too many" columns, wouldn't you just end-up creating _even more_ columns (in total) leaving MySQL / MariaDB still thinking the row size of the original table (ObjectA) is too large? I'm just provisioning an SS VM via Packer and @halkyon's "packer-web" project so I'll see...

**Comment by tractorcow** [comment]
Yep, you gotta do it manually. :)

**Comment by phptek** [comment]
Then this isn't a solution - the site is already in PROD :-(

**Comment by tractorcow** [comment]
Hmmm maybe you could make a build task to flush / archive obsolete columns?

**Comment by phptek** [comment]
Yeah...that's what I'm looking at, I could roll my own, or mod someone else's - just spotted this: https://github.com/lekoala/silverstripe-devtoolkit/blob/master/code/tasks/DropUnusedFieldsTask.php

**Comment by phptek** [comment]
....it'd need to be DROP not archive (RENAME). Otherwise InnoDB will _still_ see those fields as being part of the overall schema

**Comment by phptek** [comment]
For those coming across this issue with a "pre-existing" problem, you have two solutions, without having to split classes into two:

__Disclaimer__ This is untested anywhere other than in my Ubuntu DEV env. It also involves you as a developer knowing ahead of time the maximum possible byte-lengths of data that will eventualy populating each field you adjust:

1). (Most effective, but harder) Write a custom BuildTask that drops extraneous tables
2). (Less effective, but easier and less fraught with danger) Alter the default values passed to the `Varchar` constructor in your `$db` static.

Q: But how do I know what the new, effective row_length is?
A: Do a before and after: Run the penultimate version of the perl script found here: http://dev.mysql.com/doc/refman/5.6/en/storage-requirements.html) thus:

```
perl mysql-row-check.pl <SS_table> --tables <MyTableList>
```

Simple use-case; change `Varchar` to `Varchar(12)` in text fields used for global co-ordinates - Lat and Lon - which have a maximum (useful) length of 12 characters.

__Before:__

```
#> perl mysql-row-check.pl SS_myDb --tables MyPage | grep total
total:	58258	least: 34	columns: 376
```

__After:__

```
#> ./framework/sake dev/build flush=all
#> perl mysql-row-check.pl SS_myDb --tables MyPage | grep total
total:	58030	least: 34	columns: 376

..granted not a massive gain (loss?) but extrapolate that over several columns and multiple translations (16 in my case) and it may help to alleviate the problem. Not a long term fix - there will eventually come a time when adding further fields and locales for translation, will result in MySQL's (InnoDB's) upper row_length limit being reached.
```

**Comment by phptek** [comment]
Closing this issue. It'll still be found by searching if folks still need the info.
