### ISSUE TITLE
LocaleLink doesn't keep action or id

### ISSUE THREAD

**Issue by lekoala** [tractorcow/silverstripe-fluent#180]
When we switch lang, we lose request parameters.

I don't know what is the best way to deal with it, currently I'm doing this

https://gist.github.com/lekoala/a400f24af74461fac6f2

Any other idea?

**Comment by tractorcow** [comment]
I think we could probably add a LinkWithAction value to the result of FluentExtension::LocaleInformation() ?

However, it would only work if the target page ($this->owner) is the one handling the current request, since you don't want the actions from the current request being appended to other pages.

**Comment by wernerkrauss** [comment]
You always have to pass the action to  `$Link($action)`, so you should add it to `$LocaleLink` ?

**Comment by lekoala** [comment]
Well, the problem is that in LocaleMenu, the link is just the plain LocaleLink. I know I can override that, but it seems strange that by default we ignore action or id.

For instance, if I have a PortfolioPage with a view/slug type of detail page, if I'm on /en/portfolio/view/my-project, the LocaleLink would be /fr/portfolio for instance, skipping /view/my-project, which make language change a bit inconsistent for no reason, when LocaleLink on a page could retrieve the current action/id/otherid if needed.

**Comment by dhensby** [comment]
If you're creating custom URLs you'll need to override the `Link` function just like you would without translatable extensions...

**Comment by lekoala** [comment]
I wouldn't call using the built in /$Action/$ID pattern a "custom URL". The main problem is that LocaleLink is calling the plain "Link" method, which always return the current controller without any parameter. I hardly see how overriding the Link method would be of any help ? But any example is welcome...

**Comment by tractorcow** [comment]
I think I need a bit of context...

is `my-project` a dataobject, not a page? In which case, why not make it a page?

If you want to get it to work properly you'll need to implement link on your Project dataobject, make sure it's decorated with fluent, and then make sure that you render the template with the project (not the holding page). Which, frankly, is a lot of work....

Fluent menus just don't support linking to specific actions or non-page dataobjects, without custom code, I'm afraid.

It might be easier for you to override LocaleInformation in your page controller, and inject the modify the result to add the custom url back in.

```php

class Page extends SiteTree {
	public function LocaleInformation($locale = null) {
		$params = $this->whatever();
		$info = parent::LocaleInformation($locale);
		$info['Link'] = $info['Link'] . '/' . $params;
		return $info;
	}
}
```

**Comment by tractorcow** [comment]
Since this isn't really a bug and is more "support request" I'm going to close this. :)

**Comment by lekoala** [comment]
Indeed, if it was a page, then everything would work. It's just that sometimes it's not very convenient to extend a page. So most of the time, I have a page which displays dataobjects. But I'll do what you suggested, I'll simply override the LocaleInformation method, seems better than overriding LocaleLink.
