### ISSUE TITLE
Fluent is awesome! (Not an Issue!)

### ISSUE THREAD

**Issue by aledbrown** [tractorcow/silverstripe-fluent#182]
Just wanted to say that Fluent is absolutely awesome.

Thank you so much for creating it.

I've got it setup with SS 3.3.0-RC2 using the Fluent Master branch and it's working flawlessly.

It's about the 4th translation module I've tried and the only one that has allowed seamless translation of custom DataObjects in a way that doesn't break templates or the back end CMS at all. When you already have a single language site already setup and don't want to re-do hours and hours of work that's super important.

It's absolutely wonderful.

I don't like the YAML setup file... it's extremely difficult to work out how many spaces should be where but once you get it working ok the rest of it is astonishing. The YAML thing goes for all YAML files. Why doesn't it just read what's on the line? Why does one space or two spaces make such a vast difference? Idiotic. </rant over>

Fluent + SilverStripe = amazing. Thank you!

**Comment by tractorcow** [comment]
Haha, thanks. :)

I thought about going the way subsites did and make everything configurable in the CMS, but my main goal with fluent was to keep it simple and light, and extra interface probably wouldn't achieve that.

Thanks for testing it out, and let me know if you get any bugs working with 3.3.

**Comment by tractorcow** [comment]
I suggest setting up your IDE with a plugin to support .editorconfig, then you'll have a lot fewer issues working with yaml.
