### ISSUE TITLE
Setup should populate new language fields with original data - SSv3.3.0 RC2

### ISSUE THREAD

**Issue by aledbrown** [tractorcow/silverstripe-fluent#184]
Loving the way Fluent is working and I've not run into any serious problems from a coding or setup site yet at all.

I'm working on an a copy of a single language site that was in English. The new site is in Dutch and French.

For all of my DataObjects that are now being translated I've made MySQL queries to populate Title into Title_NL and Title_FR so that when I use the CMS and save a DO for the first time in one language it doesn't throw French in the NL field.

For SiteTree based Pages I probably should have done the same as it's annoying me while working in the CMS if I modify a French page it will save French. But then when Dutch is loaded in the CMS the English has vanished - it goes and picks up the French or visa versa. Obviously the end result is I don't want any English but for me who is inputting the changes I like to see the English in the CMS for each language so I know it hasn't been translated / input yet. It's also confusing to load a French page on the prototype site and see Dutch where there was once English. I keep having to go in and re-input English.

I'm probably going to go and write a couple of manual SQLs to update the _FR and _NL fields in SiteTree to fill the NULLs.

So, feature request:
It would be great if upon initial /dev/build that new language fields were populated automatically from whatever was in the original field. That way the CMS wouldn't ever pick up the wrong text anywhere.

I may be suffering with a Bug and I hope my suggestion / explanation makes sense. I've only ever used Fluent with SS3.3 RC2.

**Comment by tractorcow** [comment]
The way that the existing behaviour is designed is intentional.

If we were to implement the behaviour that way, ANY edits to a page would require the user to have to switch to each locale and make the same change in each locale.

By leaving the un-translated fields empty, any pages that are yet untranslated do not need to be re-edited in each locale, thereby saving time and frustration.

The problem you are encountering is probably configuration being incorrect.; You want english to be the default, but it looks as though French is ending up as the default?

Can you please post your configuration for me?

**Comment by aledbrown** [comment]
That's the problem. I'm having to constantly switch locales in the CMS to make the second language not get filled by the first language. I'd rather it kept the English I had in there to begin with.

I have the English site.
I desire a two language site with Dutch default and French as an extra.
I'm an English native and I have two people sending me translations based on the existing English site (separate thing but a great starting point).
So I go in and edit an existing page that's in English and enter in the new Dutch text, publish.
Then my French translator complains that the page she was trying to translate from English is now also populated by Dutch. I load it in the CMS and yes indeed it is populated by Dutch text not English.
It's a problem!

I can see where you're coming from. If the site was three language and keeping the English then it wouldn't be a problem. But we're getting rid of the English (and merely basing the site on the English version).

My solution is to pre-populate all the translated fields in the DB with the English via SQL manually but it's taken me a while of testing to work that out.

I just think it would be more useful since no translations exist when you're setting off on a site that the setup process should populate the copy fields with the original default. There doesn't seem to be a harm in it.

Otherwise... I'm loving Fluent. It truly is the best translation module for SilverStripe. I'll update to 3.3.0 RC3 today once I've read the release notes. Thanks.

`Fluent:
  default_locale: nl_BE
  locales:
    - nl_BE
    - fr_BE
  aliases:
    nl_BE: nl
    fr_BE: fr
`

**Comment by tractorcow** [comment]
Oh, I see.

You need to add english as a locale. You can't have English as default unless you list it.

If you want this to be the default, you need to make `default_locale: en_NZ` (or en_US, whatever locale you prefer).

**Comment by aledbrown** [comment]
Unfortunately I'm not explaining the issue properly.

There are two websites.
One is English only - it was completed and is live. It will remain English only forever.

The other website is an international website that will have the same design and graphics and same SilverStripe class files and templates. The only difference is that it will NOT be in English at all. It will be in two other languages: Dutch and French.

The two translators speak English + their native language and the web developer speaks only English + Welsh (not really useful in this case!).

Because all parties speak English and want to translate from English then it makes sense to populate all translatable fields with English. That way everyone knows where they're up to. If there's a piece of English text on the Dutch or French site that needs fixing.

However the problem is that when you input the first translation onto a page via the CMS it then gets picked up by the other language too (front end and CMS).

I believe is a valid approach to translating a site to begin from a common language and I think since you have to fill in all the fields in the CMS to make the translations anyway the setup system should populate the blank NULL fields with whatever was in the database when you set it up. That way the CMS wouldn't ever pick up something from the opposite language.

The way it currently works only makes sense only IF the new translation work is based off a language you are keeping (lazy loading). In all other cases there is no harm populating the new fields with the existing default data that resides in the database at the time Fluent setup dev/build is run.

Hopefully that makes a bit more sense now?

**Comment by tractorcow** [comment]
Ok, simple question... do you want both sites to share a single CMS and database? So
- www.mysite.com <<< english site
- www.othersite.com/ <<< second site with french / dutch locale

If this is the case, you can use a domain group to set this up. You can add this with the below config.

```yaml
Fluent:
  default_locale: en_NZ
  locales:
    - en_NZ
    - nl_BE
    - fr_BE
  aliases:
    nl_BE: nl
    fr_BE: fr
  domains:
    www.mysite.com:
      locales:
        - en_NZ
    www.othersite.com
      default: nl_BE
      locales:
        - nl_BE
        - fr_BE
```

Note that the global default DIFFERS to the site-specific default; This will ensure that the current text is treated as english, and you can apply your default workflow as you expect it to work. English text will be shown on both www.othersite.com/nl and www.othersite.com/fr until you enter translated text in either of the locales. However, it will NOT have the undesirable affect of dutch appearing on the french site... it'll stay english on the french site until you enter a translation.

You may have to do a bit of extra leg-work if you wish to dis-associate these two sites on the frontend, but it's not too hard.

To reference your recent post:

> However the problem is that when you input the first translation onto a page via the CMS it then gets picked up by the other language too (front end and CMS).

This is unavoidable unless you have three locales, I'm afraid. You cannot have an english default, a translated locale, and an un-translated locale with only two locales setup. To put things simply, you can't have more locales than columns.

With my above configuration, a partially translated column for a single table would look like:

- en_NZ - default text
- nl_BE - dutch content
- fr_BE - left blank (will inherit en_NZ on the frontend)

What you were trying to do was this

- nl_BE - english content, in the process of translating into dutch.
- fr_BE - blank for the time being, but inheriting english for untranslated fields, and (undesirably) dutch from translated fields.

Please let me know if the above suggestion suits you.

**Comment by tractorcow** [comment]
I should point out that un-translated fields inherit from the global default column, not the default for that specific domain. :)

**Comment by aledbrown** [comment]
Thanks for your reply and suggestions. I can see how what you're saying makes sense if a single database was desirable however we definitely can't have one database. The English site ultimately has additional features that are country specific and other user logins that will never be required on the international sites. The product brochure pages will be common except for their text language so it's a starting point.

I can see how the multi domain and it's pickup of the master English default will solve my temporary problem but the setup for that isn't feasible for what the client ultimately has and who will eventually look after the sites.

I don't see a downside to populating the empty fields on setup, though. It's simple and can't have mix-ups occurring. I just thought the idea might help other people too.

If populated from the start with whatever the developer has in the database from the start it clears up the undesirable behaviour of the CMS picking up cross-languages when you're in the setup phase. You're going to be overwriting it anyway but if it's not there you're seeing undesirable content all mixed up and adding confusion to a straightforward job: Make anything that is currently English on the French version French and make anything currently English on the Dutch version Dutch. No language crossing to add confusion. My layman translators can understand that. They can't work with ... "Oh, I input some of your French first and now it's all over the Dutch pages... sorry Dutch translator... who doesn't speak French."

We're not able due to company structure have a three language single site. It's one English. And another site that is Dutch/French. But all start with a copy of the existing English.

I've found my solution which is manually telling MySQL to populate those NULL fields and I've run those SQL queries (a LOT of them were required) and since then I've have had Zero problems. The CMS is behaving itself now.

**Comment by tractorcow** [comment]
OK, I'm glad you found a solution that works with you. I was about to suggest the "If fluent doesn't work perfectly, just write SQL to fix it up" solution. :)

Another thing you COULD try is add three locales to the second site, and just don't let users navigate to the english locale on the front-end (so it's only available to the back-end) via the FluentFilteredExtension (with english locale disabled by default).

But yeah, whatever works. :D

Closing this issue since you found a solution for your use case.
