### ISSUE TITLE
Feature request: Indicator for when a value is changed from the default value

### ISSUE THREAD

**Issue by robbieaverill** [tractorcow/silverstripe-fluent#188]
Assuming I have a basic Page, I install this module, and I configure two locales: en_NZ (default) and en_AU.

I change the Page's Title to "Foobar" and save it. When I move to the AU locale, the change shows through there as well. If I then change the Title at the AU locale to "Foobar Australia" and save, it shows the AU Title as expected. Navigating back to the NZ (default) locale shows "Foobar" again, as expected.

**Request:**

> Given that I have changed a value at a non-default locale level,
> I want to see a visual indicator that the value is different from the default locale's value,
> So that I am instantly aware that the value is different from the default value.
> 
> Given that I have _not_ changed a value at a non-default locale leve,
> I want to see a visual indicator that the value is the same as the default locale's value,
> So that I am instantly aware that changes will show here if changed at the default locale scope.

Hope this makes sense - it would just be a handy thing to be able to see where values are essentially "static", in that they've been customised, and will not change when the default locale's value changes.

**An example:**

In Magento, this very system is in place in the form of a checkbox with a label saying "Use default value." If the value is the same at the en_AU scope as it is at the en_NZ scope, the checkbox is ticked, and the textbox itself is in a disabled state. If you uncheck the "use default value" box, you can modify the textbox at that locale.

The implementation difference I see between that example and this module (possibly - not sure how this module works ATM) is that in Magento's ecosystem you're talking about EAV records, so by using a default value you're just _not looking for a locale value_ but going straight to the default value. Does this module copy the values from default scope to each locale on save, or does something similar exist?

Thanks for reading!

**Comment by tractorcow** [comment]
Fix at https://github.com/tractorcow/silverstripe-fluent/pull/189... thanks so much @robbieaverill !
