### ISSUE TITLE
Wrong domain in Locales()->Link

### ISSUE THREAD

**Issue by Friksel** [tractorcow/silverstripe-fluent#194]
I have a website on multiple domains /aliases. All domains point to the same website (with a locale switcher on the website), but keep their entrance domainname in urls. I want visitors to stay on the same domain they arrived at when switching locale. But that's not happening right now:

When using `$Locales` inside the template to loop through the locales to create a language switcher (like the default LocaleSwitcher.ss template) `$Link` returns an url of the current page for that locale, but with a different domainname. 
The method `domain_for_locale()` (line 332 on fluent.php) returns the first domainname supporting this locale it finds in fluent.yml. To me this is undesired behaviour. When a user choses to view a different language for a page, it should look for this new locale in the same domain. Only the language prefix/locale-alias/url-segments in the url should change.

**Comment by Friksel** [comment]
After changing domain_for_locale (line 332 on fluent.php) to return `$_SERVER['HTTP_HOST']`, the links and everything else I can see seems to work. I don't have an overview over this module like you guys, so please let me know if I'm missing something:

```
public static function domain_for_locale($locale) {
        return $_SERVER['HTTP_HOST'];
}
```

**Comment by robbieaverill** [comment]
@Friksel at a quick glance I'd assume the purpose of the `domain_for_locale` method is to pass in a locale string and return the domain for it. Your change will only return the domain for the locale that is currently active.

**Comment by Friksel** [comment]
@robbieaverill  I know. The issue isn't about that function, wich obviously works as expected. But is about the locale switcher that is using that function, where I don't want it to look for a domainname, just to switch locale. The domain should remain the same, only the locale prefix in the url should change (or be added).

So let's say a user comes in at domain B. Then he tries to switch the language from English to let's say Spanish. Suddenly the user isn't on domain B anymore, because Fluent sends the user to domain A.... only because domain A is the first domain in the config having Spanish configured (while even B has Spanish too!!!)
I could be wrong, but can't think of any reason why anybody wants it to act this way.
At least it should be configurable then, I'd say. 

Another thing is that in my fluent config I also configured localhost as a domain, for testing purposes on Wamp. I try to keep my config files on production server/live server the same as local to prevent mistakes. So far that's always working fine. And also here it should work that way. But it's not...
If I'm viewing the website on the production server and switch to another locale, it always switches to localhost.... wich obviously cannot be reached. That's not right. Again, I cannot think of any reason why it should look for other domains while just switching a locale.

**Comment by tractorcow** [comment]
@Friksel can you please post your entire config yml for me to review? That way I can better understand the structure of your website.

In your case, given you never want users to change domains when switching locales, I would say that you want no entries at all in your `domains` configuration. That way all links generated for locale-alternate versions of each page stay in the current domain.

**Comment by tractorcow** [comment]
```yaml
---
Name: myfluentconfig
After:
  - #fluentconfig
---
Fluent:
  default_locale: en_US
  locales:
    - en_US
    - es_ES
  domains: [] # Leave empty
---
Name: myfluenti18nconfig
After:
  - #fluenti18nconfig
---
i18n:
  default_locale: en_US

```

**Comment by Friksel** [comment]
@tractorcow thanks for your reaction and your time. I understand that if the domains-array in the config file will be left empty users stay on the same domain while switching locale. But as far as my understanding of this module config goes then it’s not possible to set different locales and default locales per domain. Or am I missing something and is it possible some way?

What I want to accomplish is setup different domains to have their own set of locales and default locales configured.
So for example: www.domain.es have some locals available for users to switch to with the locale switcher, but the website loads per default in Spanish.
The www.domain.com domain has locals available for users to switch too, but this domain defaults to English. The same with .nl to dutch and so on.
That is actually what I want. And this is working now with my workaround modification I did in the  module, as I described before. But it's obviously not very clean and I'd rather fix this without modifications to the module, to stay easely in sync with future versions of the module and not having to apply this modification to all future updates.
Would that be possible? 

These are the settings I have right now for fluent:

**fluent.yml inside modules _config folder:**

```
---
Name: fluentconfig
---
Fluent:
  # Don't forget to set i18n->default_locale too!
  default_locale: nl_NL
  locales: []
  aliases: []
  field_include: []
  field_exclude:
    - 'Theme'
    - '/^LocaleFilter_/i'
    - 'Priority'
  data_include: []
  data_exclude: []
  search_adapters:
    MySQLDatabase: FluentMySQLSearch
  remember_locale: false
  persist_id: 'FluentLocale'
  persist_id_cms: 'FluentLocale_CMS'
  query_param: 'l'
  detect_locale: false
  force_domain: false
  domains: []
---
Name: fluenti18nconfig
---
i18n:
  default_locale: nl_NL
```

**fluent.yml in mysite\_config:**

```
---
Name: myfluentconfig
After: '#fluentconfig'
---
# MAIN SETTINGS
Fluent:
  default_locale: nl_NL
  locales:
    - nl_NL
    - en_US
    - es_ES
  aliases:
    nl_NL: nl
    en_US: en
    es_ES: es
  field_include: []
  field_exclude: []
  data_include: []
  data_exclude: []
  search_adapters:
    MySQLDatabase: FluentMySQLSearch
  remember_locale: false
  persist_id: 'FluentLocale'
  persist_id_cms: 'FluentLocale_CMS'
  query_param: 'l'
  detect_locale: false
  force_domain: false
  domains:
    localhost:
      locales:
        - nl_NL
        - en_US
        - es_ES
      default_locale: nl_NL
    mytestserver.nl:
      locales:
        - nl_NL
        - en_US
        - es_ES
      default_locale: nl_NL
    mylivedutchdomain.nl:
      locales:
        - nl_NL
        - en_US
        - es_ES
      default_locale: nl_NL
    myliveenglishdomain.com:
      locales:
        - nl_NL
        - en_US
        - es_ES
      default_locale: en_US
    mylivespanishdomain.es:
      locales:
        - nl_NL
        - en_US
        - es_ES
      default_locale: es_ES
    someshadowdomainA.org:
      locales:
        - nl_NL
        - en_US
        - es_ES
      default_locale: en_US
    someshadowdomainB.nl:
      locales:
        - nl_NL
        - en_US
        - es_ES
      default_locale: nl_NL
---
Name: myfluenti18nconfig
After: '#fluenti18nconfig'
---
i18n:
  default_locale: nl_NL
---
```

**Comment by tractorcow** [comment]
> But as far as my understanding of this module config goes then it’s not possible to set different locales and default locales per domain. Or am I missing something and is it possible some way?

I'm sorry but fluent doesn't support multiple content across different domains, as it violates the DRY rule for SEO, which is to (ideally) avoid duplicating content at multiple physical urls. If you have one piece of content, it should have one canonical URL.

If you run the validation task at https://github.com/tractorcow/silverstripe-fluent/blob/master/code/tasks/FluentValidateTask.php you'll get the appropriate error about some locales being assigned to multiple domains.

A possible solution for your use case is to simply remove all domain configuration, and have a custom script that redirects users to the correct home page URL based on domain.

This script could be in your _config.php, your home page controller, or even in a request filter to handle requests before routing.

E.g. pseudocode

```
if(REQUEST_URI === '/'){
  switch(domain) {
  	case 'domaina':
  	case 'domainb':
  	  return redirect('/nl');
	case 'domainc':
  	case 'domaind':
  	  return redirect('/es')
 	default:
  	  return redirect('/en');
  }
}
```

**Comment by Friksel** [comment]
Ah, okay, I see now. You're right. I don't know that much about duplicated content in SEO, but you got me re-thinking the setup. I want to stay DRY. I'll probably stick to two main domains, each with unique languages then. Good to know now before the website will go live. Thanks for pointing that out!

**Comment by tractorcow** [comment]
Thanks @Friksel and hope that my feedback actually does help your progress. :)

I'll focus my attention on https://github.com/tractorcow/silverstripe-fluent/issues/200 for now, so that we can help get your site live in time. Do you have a date for this?
