### ISSUE TITLE
"Translatable field" label not showing next to additional fields

### ISSUE THREAD

**Issue by Faloude** [tractorcow/silverstripe-fluent#195]
I've created an additional TextField called `Introduction` on `HomePage` (Which extends `Page`, and then extends `SiteTree`) and added the code to make this new field translatable:

`private static $translate = array(
        'Introduction'
    );`

Everything works just fine, but in the back-end there is no green flag icon that indicates that the field is translatable:

![issue](https://cloud.githubusercontent.com/assets/18635312/14763968/3918247e-09a7-11e6-8cbd-9cd21e77ad42.jpg)

**Comment by tractorcow** [comment]
Please follow the instructions at https://github.com/tractorcow/silverstripe-fluent/blob/master/docs/en/dataobjects.md#default-field-scaffolder and you'll have no more trouble. :)
