### ISSUE TITLE
Improvement: Document how to add Fluent to an extension

### ISSUE THREAD

**Issue by robbieaverill** [tractorcow/silverstripe-fluent#196]
Assuming I have a DataObject like so:

```php
class Player extends DataObject
{
    private static $db = [
        'PlayerName' => 'Varchar(255)',
        'IrrelevantField' => 'Text'
    ];
}
```

...and I have an extension for it like so:

```php
class PlayerExtension extends DataExtension
{
    public function updateCMSFields(FieldList $fields)
    {
        $fields->removeByName('IrrelevantField');
    }
}
```

It would be great if the documentation could explain how you could add the Fluent extension to Player. At this point it seems that the FluentExtension conflicts with the PlayerExtension because they both use the `updateCMSFields()` method.

The docs currently say that `it is necessary to ensure that the updateCMSFields extension method is called once (and only once) on each FieldList object`, but doesn't explain how to use (or modify for Fluent use) code like the above.

**Comment by robbieaverill** [comment]
For example, I can modify my extension to `extend FluentExtension`, then call `parent::updateCMSFields($fields)` and it appears to work:

```php
class PlayerExtension extends FluentExtension
{
    public function updateCMSFields(FieldList $fields)
    {
        $fields->removeByName('IrrelevantField');
        parent::updateCMSFields($fields);
    }
}
```

**Comment by robbieaverill** [comment]
Another thing I noticed is that I'm having a lot of trouble with a custom FormField type that I've added - it's an extension of a `TextareaField`, and if I add it to `data_includes` then it will display the localisation icon, and the values are saved to the DB in the right place, but it always puts the default locale's value into the field when I load the CMS page.

**Comment by tractorcow** [comment]
Yep your second comment is pretty much the best way to do it. 

> Another thing I noticed is that I'm having a lot of trouble with a custom FormField type that I've added - it's an extension of a TextareaField, and if I add it to data_includes then it will display the localisation icon, and the values are saved to the DB in the right place, but it always puts the default locale's value into the field when I load the CMS page.

I suggest debugging the queries with `showqueries=1` in your querystring to check how that field is being queried.

**Comment by robbieaverill** [comment]
Thanks @tractorcow - regarding the custom form field, I'll do that. I've put the task off until the end of the week to try again with a fresh mind, but that time has come around now :)

I'll make a PR to your docs shortly for the extension example

**Comment by robbieaverill** [comment]
Hi again @tractorcow 

I've done a bit of testing so far on this and can report the following:

* Markdown field added directly to a DataObject using `getCMSFields()`, *and* being added with `$this->beforeUpdateCMSFields()` works fine  :white_check_mark:
* As above, *without* using `beforeUpdateCMSFields()` doesn't work (expected, I read the docs ;))
* Markdown field added using an extension to a DataObject using `updateCMSFields` **or** using `$db` with no `updateCMSFields`

**Comment by robbieaverill** [comment]
I'm getting a little closer with debugging. I've taken a look at the SQL queries that are run to get the data for each of the DataObjects where the first one isn't showing the correct locale value (field is added via extension) and the second one is (field is owned directly by the DataObject), and the differences are:

### Not working

```sql
CASE
   WHEN `Widget`.`ClassName` IN ('MyContent', 'MyRecipe') THEN `MyContent`.`Markdown`
   WHEN `Widget`.`ClassName` IN ('MyRecipe') THEN `MyRecipe`.`Markdown`
   ELSE NULL
END AS `Markdown`,
CASE
   WHEN `Widget`.`ClassName` IN ('MyContent', 'MyRecipe') THEN `MyContent`.`TestStandardTextField`
   WHEN `Widget`.`ClassName` IN ('MyRecipe') THEN `MyRecipe`.`TestStandardTextField`
   ELSE NULL
END AS `TestStandardTextField`,
```

### Working

```
CASE COALESCE(CAST(`MyVideo`.`VideoURL_en_GB` AS CHAR), '')
    WHEN '' THEN `MyVideo`.`VideoURL`
    WHEN '0' THEN `MyVideo`.`VideoURL`
    ELSE `MyVideo`.`VideoURL_en_GB`
END AS `VideoURL`,
CASE COALESCE(CAST(`MyVideo`.`VideoDescription_en_GB` AS CHAR), '')
    WHEN '' THEN `MyVideo`.`VideoDescription`
    WHEN '0' THEN `MyVideo`.`VideoDescription`
    ELSE `MyVideo`.`VideoDescription_en_GB`
END AS `VideoDescription`,
```

Obviously the working example is a product of `FluentExtension::localiseSelect` - do you have any idea why the other example is behaving differently?

**Comment by robbieaverill** [comment]
Gah!!  Here's the issue:

* `MyContent` extends `Widget`
* `MyRecipe` extends `MyContent`
* If I change `MyRecipe` to extend `Widget` instead, everything is fine

Silver lining: I'll finish off that PR :)

**Comment by tractorcow** [comment]
Oh, one more thing.

If you're translating a dataobject, you MUST add the fluent extension to the base class, not the subclass.

E.g., in your above example, you have two classes that extend Widget. You need to add FluentExtension to Widget, not your custom classes. :D

**Comment by tractorcow** [comment]
I really need to add a sanity check into FluentExtension to throw exceptions if applied at the wrong level. :P

**Comment by robbieaverill** [comment]
Yes please!

On Thursday, 28 April 2016, Damian Mooyman <notifications@github.com> wrote:

> I really need to add a sanity check into FluentExtension to throw
> exceptions if applied at the wrong level. :P
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/tractorcow/silverstripe-fluent/issues/196#issuecomment-215326656>
>


-- 
*Robbie Averill*
LA PETITE MANOUCHE - NZ Gypsy Jazz Guitar Duo
Phone: +64 27 321 4758
contact@lapetitemanouche.com
www.lapetitemanouche.com

**Comment by robbieaverill** [comment]
Good call - I've adjusted my configuration so that I have:

```yaml
---
Name: mycontentextensions
---
MyContent:
  extensions:
    - MyContentExtension
MyRecipt:
  extensions:
    - MyContentExtensions
```

Then:

```yaml
---
Name: myfluentextensions
After:
  - '#mycontentextensions'
---
Widget:
  extensions:
    - FluentExtension
```

It's working well. I'm not sure whether the "after" part is the reason for the order or not, but it's working :) Want me to update the PR to mention that somewhere?

**Comment by tractorcow** [comment]
you're fine. :D

Closing since https://github.com/tractorcow/silverstripe-fluent/pull/197 is merged.
