### ISSUE TITLE
Visual indicator: Resetting to default locale value doesn't work on TextareaFields

### ISSUE THREAD

**Issue by robbieaverill** [tractorcow/silverstripe-fluent#198]
Just logging this as a bug for reference, I will patch it tomorrow.

The "Click here to reset to the default value" visual indicator button works for text inputs, but not for textareas.

Looks like the problem is to do with how the default value (JSON encoded) is inserted into the DOM. Will probably need to be escaped first.

Caused by #189

**Comment by tractorcow** [comment]
Yeah I noticed that... just related to them having a slightly different js interface, I guess? :P

It's not perfect, but it's still better than it was before. :)

**Comment by robbieaverill** [comment]
No biggy, it shouldn't take long to resolve :)
