### ISSUE TITLE
very hard to find on addons

### ISSUE THREAD

**Issue by sunnysideup** [tractorcow/silverstripe-fluent#206]
Hi

I looked for this module on addons.silverstripe.org and I found it impossible to find. 

- http://addons.silverstripe.org/add-ons?search=**translatable**
- http://addons.silverstripe.org/add-ons?search=**translatable**&type=&sort=&start=16
- http://addons.silverstripe.org/add-ons?search=**internationalisation**&type=&sort=
- http://addons.silverstripe.org/add-ons?search=**i18n**&type=&sort=
**- http://addons.silverstripe.org/add-ons?search=localisation&type=&sort= ... this is the only one that works....**

**Comment by phptek** [comment]
@sunnysideup as you'll know, this is functionality is likely dictated by the terms used in `composer.json` which are currently:

    ["silverstripe", "localisation", "localization", "translation", "language", "locale", "multilingual"]

..which prob explains why "localisation" is the only term that worked.

**Comment by tractorcow** [comment]
I've taken on board your suggestions. :D
