### ISSUE TITLE
Dropdown map to Dataobject 

### ISSUE THREAD

**Issue by leafnetjake** [tractorcow/silverstripe-fluent#210]
When mapping a dataobject to a dropdown field whilst using fluentextension a frontend 'error' is thrown.

**Example:**
```
$hotel = Dataobject::get("Lodge")->map("ID", "Title", "Select a hotel");
$fields->push(DropDownField::create(
        'HotelID', 
        'Select Hotel Page:',
         $hotel
)->setEmptyString("-- Select Hotel --") );

```
The error is invoked as soon as $Hotel is referenced in the template.

**Comment by stevie-mayhew** [comment]
What is the error? 

`->map` only takes two arguments, the `keyField` and the `titleField`. You can also change this to an array which may solve your problem:

`$hotel = Lodge::get()->map("ID", "Title")->toArray();`

**Comment by leafnetjake** [comment]
I've tried the array however still no dice.

The error displayed is the generic template error, dev environment provides no specifics.

> Sorry, there was a problem with handling your request.

Template call is just $Hotel.Title

**Comment by tractorcow** [comment]
That normally happens when you have a CSRF error. Are you testing this locally or on a test server? set your environment to 'dev' to try to get more output.

**Comment by tractorcow** [comment]
> $hotel = Dataobject::get("Lodge")->map("ID", "Title", "Select a hotel");


Also, map doesn't take three parameters. :)

**Comment by stevie-mayhew** [comment]
Can you post your template @leafnetjake ?

We might be able to spot whats going on there :)

**Comment by leafnetjake** [comment]
Thanks for the prompt replies!

Thanks also for pointing out the parameters there, missed that one whilst frantically trying to figure this thing out.

I was able to replicate this issue on both a local and test server, both in dev mode. This is where I'm very confused as there is no warning/error other than the generic template error. The process to replicate this issue was to create the 'Lodge' dataobject first. Once 'Lodge' locales were filled and saved I then created the 'Hotel' dataobject. Once the 'Hotel' dataobject was saved I receive the template error. If I revisit the 'Lodge' dataobject and re-save without any changes the error is longer present. Yet, if I head to the 'Hotel' dataobject and save it again as the 'last step' I'm getting the same template error.

I tried dropping the tables from the DB and performed a dev/build however I received the same error.

I've was finally able to resolve this issue by renaming the two objects and dropping all associated tables. Since then I have been unable to replicate this issue.

It seems this is not a fluent issue and is rather something going strangely wrong at a time I wasn't paying attention or ... I don't even know. But the good news is the issue is resolved, the sad news.. I won't fully understand what happened.

For reference, I was using the following:

```
  private static $has_one = array (
        'Hotel' => 'Lodge',
    );
```

```
$hotel = Dataobject::get("Lodge")->map("ID", "Title");
$fields->push(DropDownField::create(
        'HotelID', 
        'Select Hotel Page:',
         $hotel
)->setEmptyString("-- Select Hotel --") );

```

```
<% if Hotel %>
<figure class='item'>
<% if Image %>
$CroppedImage(320,200)
<% end_if %>
<figcaption>
<h2>$Hotel.Title</h2>
<div class='more'>	
</div>
</figcaption>
</figure>
<% end_if %>
```

**Comment by tractorcow** [comment]
Ok, I did a bit more looking.

That error is coming from the default error page content. This means that there's an error somewhere, but your error display settings are suppressing the actual message.

I have a feeling that it's not related to fluent, but since you found your solution, it's ok to close this?

Sorry I couldn't help more, but good job on fixing your issue!
