### ISSUE TITLE
Use of Browser navigation buttons causes confusion

### ISSUE THREAD

**Issue by phptek** [tractorcow/silverstripe-fluent#211]
When using a browser's "Back" and "Forward" buttons, I can reproduce a scenario where what is displayed in the CMS' locale switcher, differs from the locale saved in the `FluentLocale_CMS` cookie and what is displayed in the admin URL's GET param represented by `Fluent::query_param`.

For step-by-step reproduction, see comment no's 20-22 in #191.

**Comment by tractorcow** [comment]
Yes, that will be an issue where relying on session variables to store the current locale.

I guess a more aggressive querystring-type persistency may be necessary, ala-translatable, in lieu of a better state management API.

**Comment by tractorcow** [comment]
Also, I'd probably add a composer `conflict` to translatable if doing this. :) Anyone need translatable AND fluent in the same project?

**Comment by phptek** [comment]
@tractorcow viz Translateable and Fluent agree - where I'd diverge is when using CWP and not wanting to slow the thing down any more than it is, with separate SiteTree's ala Translateable.

**Comment by tractorcow** [comment]
I lament the lack of time I have to actually fix the bugs in fluent. =(

**Comment by phptek** [comment]
What we need to ask is: What is the expected default behaviour from a CMS users' perspective on the value of cookies and UI state driven from this data, when using browser navigation.

As a CMS user, my feel is that once I have "set" something, it should stay "set" until such time as I elect to "unset" it. It follows therefore that the cookie-value changing as it does on "forward" and "back", is the buggy thing and not the locale switcher's selected UI state as I have described the issue.

My quick browse of the Netscape cookie spec doesn't seem to yield anything on how cookies should behave with respect to browser navigation.

**Comment by phptek** [comment]
> I lament the lack of time I have to actually fix the bugs in fluent. 
Ah the old "Develop it and they will come" which turns into "Duck!"...

I actually do have some time, I just need guidance on best approach for the specific issues I've reported :-)

**Comment by tractorcow** [comment]
The main reason for the session variable is so that sub-requests (those initiated via ajax handlers) "inherit" all locale state from the main request (as per the user-visible URL). Translatable had an issue with this in that sub-requests had to have the locale querystring parameter added explicitly, or it'd set the wrong locale.

So in our case, ensuring that the locale querystring is always present, and that the dropdown matches the "actual" locale, should be the resolution to many of the quirks in fluent.

**Comment by phptek** [comment]
> So in our case, ensuring that the locale querystring is always present, and that the dropdown matches the "actual" locale, 

And on paper that sounds good, but doesn't help the scenario I describe above with regard to user-expectation. Using the back button will obviously change the query string param to what it was when that "page" was last visited. It follows then that relying on this value will still change the session and cookie values, thus automatically (bad) unsetting that which the user has manually set.

If we go ahead with something like this, it will remove _some_ confusion ala "What locale am I _really_ in?", but not _all_ confusion ala "why did my locale switch to something else when I didn't tell it to?".

**Comment by tractorcow** [comment]
> Using the back button will obviously change the query string param to what it was when that "page" was last visited. 

I guess that's what I would expect it to... if I had changed the locale selected, then pressed "back", I'd expect it to go back to the locale before I'd set it?

**Comment by phptek** [comment]
> , then pressed "back", I'd expect it to go back to the locale before I'd set it?

If by "I" you mean "Me as developer" and not "Me as naive content author"

**Comment by phptek** [comment]
Regardless, I think might just be my nitpicking. Having the switcher display the _actual_ cookie-value as locale, would satisfy the original bug as I reported it for the time being :-)

**Comment by tractorcow** [comment]
I guess we need to decide first what is the expected behaviour before progressing.

If we decide that the current locale is NOT a part of the url state then we probably should never use querystring to set the locale.

If we decide that the current locale IS a part of the url, then we need to make the current locale (and switches between locale) prominent to the user when they navigate through the CMS.

**Comment by phptek** [comment]
> If we decide that the current locale is NOT a part of the url state then we probably should never use querystring to set the locale.

1. Speaking as a purist with regard to what I believe users expect: "Stuff should not change if I didn't tell stuff to change". Period.

2. Speaking as a pragmatist; "If the system keeps me up-to-date with regard to its current state, and _I can rely on it_, then I'm happy".

For now, let's go with 2. What do you think?

**Comment by tractorcow** [comment]
number 2 is easiest for us to enforce. :) It's also the way the module is attempting to behave as.

**Comment by phptek** [comment]
Cheers @tractorcow I'll give it a crack.

**Comment by tractorcow** [comment]
Awesome, thanks @phptek :D

**Comment by phptek** [comment]
@tractorcow Can you see anything wrong with this approach? I've never been hot on the CMS' internal entwine calls, so I'm prepared for `redraw` not being the best place to put this logic.
