### ISSUE TITLE
Fluent::detect_browser_locale it's never being called

### ISSUE THREAD

**Issue by tony13tv** [tractorcow/silverstripe-fluent#218]
I tried to make my site "detect browser locale" through configuration but it didn't work.

Doing some debug I found out that there was a rule for '/' that sets the ```query_param``` to ```Fluent::default_locale(true)``` but that was breaking the ```detect_browser_locale``` feature.

So I commented it out. I want to know if I should PR this change or maybre create a config param to handle this use case.

**Comment by phptek** [comment]
@tony13tv Thanks. What would really help is if you gave a _detailed description_ of what _exactly_ "didn't work" and then create a PR for it. The PR doesn't _have to get merged_ it's simply a good basis on which other dev's can get a look at your code.

Ideally, if you can easily write a failing test that demonstrates the problem, this is always preferable. Once a maintainer can see that the test passes after writing a "fix" for something, they can know much more intelligently that the problem really is "Fixed".

Cheers :-)

**Comment by tractorcow** [comment]
You're right, it doesn't work. It hasn't worked properly for a while, so I've turned it off by default. It tends to have very unreliable behaviour.

This should fix your bug https://github.com/tractorcow/silverstripe-fluent/pull/220

**Comment by tony13tv** [comment]
It does work now! Thank you.

**Comment by phptek** [comment]
@tony13tv Keen to close this then? :-)

**Comment by tractorcow** [comment]
Fixed with https://github.com/tractorcow/silverstripe-fluent/pull/220
