### ISSUE TITLE
Feature: Locale page indicator

### ISSUE THREAD

**Issue by tractorcow** [tractorcow/silverstripe-fluent#221]
When editing a page there should be a generic "locale indicator" to inform the user which locale this page will be saved in. This indicator should also tell the user if this is the default locale (or not) so that users doing initial data-entry of pages can be prompted to switch.

**Comment by phptek** [comment]
Something like the "two-tone" build status SVGs included in many GIT repos might be a good start? LHS (Blue: = Current locale) RHS (Green: Default Locale) - or vice versa....although ioS users may think it's some sort of button...

**Comment by tractorcow** [comment]
Yeah I think colour is a good way to get different states across. :)
