### ISSUE TITLE
Undefined index issue on dev-master

### ISSUE THREAD

**Issue by sanderha** [tractorcow/silverstripe-fluent#226]
Hey guys 

I just wanted to try a recent fix that was merged into master regarding not being able to totally clear translated fields (issue #204 ). It works.. But not without throwing the following error aswell: 

```
ERROR [Notice]: Undefined index: fields
IN POST /admin/pages/edit/EditForm
Line 723 in /Applications/MAMP/htdocs/casoefurniture/fluent/code/extensions/FluentExtension.php
``` 
The code at line 723:
```php 
                if (!array_key_exists($field, $updates['fields'])) {
                    continue;
                }
``` 

Not sure if there should be a check for the "fields" index aswell?

**Comment by mleutenegger** [comment]
There should be one, as `isset()` did not care about "fields" being present and `array_key_exist()` does... Looks like this has already been done.
