### ISSUE TITLE
Installation documentation needs update

### ISSUE THREAD

**Issue by RVXD** [tractorcow/silverstripe-fluent#228]
In the installation instructions this is mentioned:
composer require "tractorcow/silverstripe-fluent" "3.1.*-dev"

You wil get and old version of Fluent if you use it.
Maybe change it to:
composer require "tractorcow/silverstripe-fluent" "3.5.*-dev"

**Comment by dhensby** [comment]
`composer require tractorcow/silverstripe-fluent ^3.5`

**Comment by tractorcow** [comment]
Thanks, fixed!
