### ISSUE TITLE
page hidden in a language is accessible via the localmenu template

### ISSUE THREAD

**Issue by guyvanbael** [tractorcow/silverstripe-fluent#229]
This doesn't seem to work:
inactive (if the page is not viewable in the current locale - Link goes to the locale home page)

I have pages who are hidden from menu in another language (English) but when the page is viewed in the default language (dutch) and user clicks the languagechoice Englisch in the localmenu template, the user is redirected to the english version of that page even though its hidden from the menu. Is there a way to avoid this?

UPDATE:
FluentExtension.php contains this piece of code where linkingmode is set. I guess this check isn't correct so 'invalid' is never set.

        // Check linking mode
        $linkingMode = 'link';
        if ($this->owner->hasMethod('canViewInLocale') && !$this->owner->canViewInLocale($locale)) {
            $linkingMode = 'invalid';
        } elseif ($locale === Fluent::current_locale()) {
            $linkingMode = 'current';
        }

**Comment by guyvanbael** [comment]
made this changes to fluentextenstion.php to make it work. Maybe @tractorcow can implement this in the core code?

        // Return locale root url if unable to view this item in this locale
        if ($this->owner->hasMethod('showInMenusInLocale') && !$this->owner->showInMenusInLocale($locale)) {
            return $this->owner->BaseURLForLocale($locale);
        }

        // Check linking mode
        $linkingMode = 'link';
        if ($this->owner->hasMethod('showInMenusInLocale') && !$this->owner->showInMenusInLocale($locale)) {
            $linkingMode = 'invalid';
        } elseif ($locale === Fluent::current_locale()) {
            $linkingMode = 'current';
        }

**Comment by tractorcow** [comment]
Thanks @guyvanbael I'll check it out. ;)

**Comment by tractorcow** [comment]
> I have pages who are hidden from menu in another language (English) but when the page is viewed in the default language (dutch) and user clicks the languagechoice Englisch in the localmenu template, the user is redirected to the english version of that page even though its hidden from the menu. Is there a way to avoid this?

Hm, I wonder if this is a mis-understanding of the feature; The menu filtering is meant to hide this page from the top level menus in certain locales, it's not ment to make those pages inaccessible.

What you want to use is the FluentFilteredExtension, which will make that page inaccessible in the way you are expecting it to.
