### ISSUE TITLE
using fluent breaks Silverstripe's breadcrumbs

### ISSUE THREAD

**Issue by guyvanbael** [tractorcow/silverstripe-fluent#230]
After adding fluent to a website only the page you 're on shows up in the breadcrumbs.
![schermafbeelding 2016-09-29 om 11 29 06](https://cloud.githubusercontent.com/assets/3098809/18948589/fabd531c-8637-11e6-8f87-3faca9fce838.png)

**Comment by tractorcow** [comment]
Hi @guyvanbael , what are you putting in your template? Is it just `$Breadcrumbs`?

It may be that I need to work on a fluent-friendly BreadcrumbsTemplate.ss or Breadcrumbs method.

**Comment by guyvanbael** [comment]
Hi @tractorcow , i'm just using breadcrumbs.  It's the getBreadcrumbItems function in cms's SiteTree.php that has a check on showinmenu that's causing the issue.

if($showHidden || $page->ShowInMenus || ($page->ID == $this->ID)) {
				$pages[] = $page;
			}

Thanks for looking into it. It's the first time that i use fluent instead of translatable and i like it a lot!

**Comment by tractorcow** [comment]
Is your ShowInMenus config being customised? Maybe disabling that would fix it. :D

There is a separate extension for fluent-enabled menu. Are you using FluentMenuExtension?

**Comment by guyvanbael** [comment]
Yes i'm using FluentMenuExtension

**Comment by guyvanbael** [comment]
using FluentFilteredExtension instead of FluentMenuExtension seems to solve the issue.
