### ISSUE TITLE
Language switcher with shortened names

### ISSUE THREAD

**Issue by cheatus** [tractorcow/silverstripe-fluent#240]
Hi there, 
I was wodnering if it's possible to change displayed names from "English (United States)" to something like "EN" in language switcher? 

Thanks,
D.

**Comment by tractorcow** [comment]
Not without a bit of work...

I think what we need is an extension in FluentExtension::LocaleInformation() so you can inject custom properties such as this.

Something like this?

https://github.com/tractorcow/silverstripe-fluent/blob/master/code/extensions/FluentExtension.php#L423

```php
public function LocaleInformation($locale = null)
{
	// ...
	$data = $this->owner->extend('updateLocaleInformation', $data, $locale);
	return new ArrayData($data);
}
```

**Comment by cheatus** [comment]
Hi tractorcow,
thank you for your answer. I think I've found a simpler approach tho, correct me if I'm wrong.

I've used $Language variable in my menu template so it looks like this:

`

    <li class="$LinkingMode">
      <a href="$Link.ATT" class="language-label">$Language.XML</a>
    </li>

`

... then just styled "a href" with "language-label" class.

What do you think?

Cheers,
D.

**Comment by tractorcow** [comment]
oh, that's it, good job!
