### ISSUE TITLE
Need to throw error if FluentExtension is applied to any class more than once

### ISSUE THREAD

**Issue by tractorcow** [tractorcow/silverstripe-fluent#241]
Raised at https://github.com/tractorcow/silverstripe-fluent/issues/191

This error needs to both raise the exception and provide enough information to show where the extension is added a second time.

This will fix lots of problems. :)

Potentially this could be added to FluentValidateTask as a warning rather than being a hard error.

**Comment by tractorcow** [comment]
Fixed with https://github.com/tractorcow/silverstripe-fluent/pull/242

**Comment by phptek** [comment]
A bit late to the party here, but don't we (SS devs) have bigger problems if framework is willing to apply extensions multiple times?

**Comment by dhensby** [comment]
> A bit late to the party here, but don't we (SS devs) have bigger problems if framework is willing to apply extensions multiple times?

Probably, we could raise an issue on framework?
