### ISSUE TITLE
Google Sitemap Missing Return Links ("Incorrect hreflang implementation")

### ISSUE THREAD

**Issue by purplespider** [tractorcow/silverstripe-fluent#246]
I've just received an e-mail from Google saying there is an "Incorrect hreflang implementation" on a site using Fluent I launched a few weeks ago.

Specifically, it seems to be reporting: "Sitemap provided URLs and alternative URLs in 'fr-FR' that do not have return tags."

Looking into this a bit further it seems that currently Fluent generates a sitemap that lists all the pages for the default locale, and for each of them provides links to that page in the other locales.

However, it seems that it should *also* be listing all the pages in the other locales with links back to the default locale (and the other locales).

From [Google's Guidelines](https://support.google.com/webmasters/answer/189077?hl=en):

> If page A links to page B, page B must link back to page A. If this is not the case for all pages that use hreflang annotations, those annotations may be ignored or not interpreted correctly.

**Comment by tractorcow** [comment]
Are you using the google sitemaps module? Or is the error coming from the meta tags in each page head?

Can you please dump the <head> of each of your pages for me, and I can investigate in the mean time. :)

**Comment by tractorcow** [comment]
In my test site, all of my header tags are the same (regardless of locale).

```html
<link rel="alternate" hreflang="en-US" href="http://fluenttest.loc/" />
	<link rel="alternate" hreflang="en-NZ" href="http://fluenttest.loc/nz/" />
	<link rel="alternate" hreflang="en-AU" href="http://fluenttest.loc/au/" />
	<link rel="alternate" hreflang="en-PH" href="http://fluenttest.loc/ph/" />
	<link rel="alternate" hreflang="en-SG" href="http://fluenttest.loc/sg/" />
	<link rel="alternate" hreflang="en-GB" href="http://fluenttest.loc/uk/" />
```

Is it possible that you've configured your domain name slightly incorrectly, so that the urls don't match the href exactly?

Can you look at the last answer in http://webmasters.stackexchange.com/questions/67058/international-targeting-no-return-tags and tell me which of these might apply to your site?

**Comment by purplespider** [comment]
Sorry for the delay after your fast response! It's about time I sorted this.

I'm using the Google Sitemaps module, which I believe is then extended by Fluent.

The sitemap in question is here: http://www.campingquinquis.com/sitemap.xml/sitemap/SiteTree/1

You can see in the XML that each page is listed once as a url->loc (using the main locale), and each then has 3 links (one for each locale, including the main one).

I believe that this should all be repeated a further 2 times, for the other 2 locales, so that there are also url->loc items for the other locales.

From that StackExchange answer, the 3rd point may be the same issue I'm having.

**Comment by robbieaverill** [comment]
We've done further work to make the sitemap template compliant in the SilverStripe 4 version of Fluent. Please reopen if you feel this is still an issue, otherwise let's consider this resolved in Fluent for SilverStripe 4.

**Comment by purplespider** [comment]
Sorry, but this issue still seems to existing with the latest version on SilverStripe 4.

Take this correct sitemap example from [Google's own docs](https://support.google.com/webmasters/answer/189077#sitemap):

````xml
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:xhtml="http://www.w3.org/1999/xhtml">
  <url>
    <loc>http://www.example.com/english/page.html</loc>
    <xhtml:link 
               rel="alternate"
               hreflang="de"
               href="http://www.example.com/deutsch/page.html"/>
    <xhtml:link 
               rel="alternate"
               hreflang="de-ch"
               href="http://www.example.com/schweiz-deutsch/page.html"/>
    <xhtml:link 
               rel="alternate"
               hreflang="en"
               href="http://www.example.com/english/page.html"/>
  </url>
  <url>
    <loc>http://www.example.com/deutsch/page.html</loc>
    <xhtml:link 
               rel="alternate"
               hreflang="de"
               href="http://www.example.com/deutsch/page.html"/>
    <xhtml:link 
               rel="alternate"
               hreflang="de-ch"
               href="http://www.example.com/schweiz-deutsch/page.html"/>
    <xhtml:link 
               rel="alternate"
               hreflang="en"
               href="http://www.example.com/english/page.html"/>
  </url>
  <url>
    <loc>http://www.example.com/schweiz-deutsch/page.html</loc>
    <xhtml:link 
               rel="alternate"
               hreflang="de"
               href="http://www.example.com/deutsch/page.html"/>
    <xhtml:link 
               rel="alternate"
               hreflang="de-ch"
               href="http://www.example.com/schweiz-deutsch/page.html"/>
    <xhtml:link 
               rel="alternate"
               hreflang="en"
               href="http://www.example.com/english/page.html"/>
  </url>
</urlset>
````

Fluent is not currently doing this, it is currently doing the following:
````xml
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:xhtml="http://www.w3.org/1999/xhtml">
  <url>
    <loc>http://www.example.com/english/page.html</loc>
    <xhtml:link 
               rel="alternate"
               hreflang="de"
               href="http://www.example.com/deutsch/page.html"/>
    <xhtml:link 
               rel="alternate"
               hreflang="de-ch"
               href="http://www.example.com/schweiz-deutsch/page.html"/>
    <xhtml:link 
               rel="alternate"
               hreflang="en"
               href="http://www.example.com/english/page.html"/>
  </url>
</urlset>
````

i.e. it's not creating `<url>`s for each locale, only the main one.
