### ISSUE TITLE
All translated fields on one place

### ISSUE THREAD

**Issue by mrProper666** [tractorcow/silverstripe-fluent#250]
This is excellent module.
Anyway I have an admin question. I have a DataObject with some text fields and they have been marked as translated (with $translated = array....). Everything works fine with language switching from the green dropdown.
Here is my issue - is it possible transated fields for the different languages (e.g. Title_en_US, Title_bg_BG, Title_ru_RU.....) to be listed all together and thus to be skipped language switching from the dropdown and save the DataObject with one click?
Is there a way to switch off or disable temporarily Fluent?

**Comment by tractorcow** [comment]
You can add fields directly for those locales. It requires a bit of logic to work around the fact that `Field` will invisibly be rewritten to the `Field_<currentlocale>`, but you can go ahead and add textfields for `Field_<otherlocale>` and it'll save as per normal.

**Comment by mrProper666** [comment]
Thanks tractorcow, I'll give it a try.
