### ISSUE TITLE
virtual pages navigation label not set

### ISSUE THREAD

**Issue by oetiker** [tractorcow/silverstripe-fluent#253]
With fluent installed, it seems that the 'Navigation label'  in virtual pages does NOT get properly set (it stays on New Virtual Page). The workaround is to 're-publish' the original page which will then cause the navigation labels of the virtual pages to be re-written ... but only in the current language ... so the master page has to be re-published in each language separately ...

**Comment by tractorcow** [comment]
If I recall correctly, SiteTree has an "optimisation" that leaves the page MenuTitle empty if it === page Title. This behaviour can cause odd issues when installed with fluent.

This line of code ATTEMPTS to fix it.

https://github.com/tractorcow/silverstripe-fluent/blob/master/code/extensions/FluentSiteTree.php#L20

Does the issue minimise (if not disappear completely) without this fix?

**Comment by oetiker** [comment]
yes, if I remove that line, the issue disappears

**Comment by tractorcow** [comment]
@oetiker is https://github.com/tractorcow/silverstripe-fluent/pull/254 ok?

**Comment by oetiker** [comment]
perfect!

**Comment by tractorcow** [comment]
Fixed and tagged 3.8.1
