### ISSUE TITLE
SS4 support

### ISSUE THREAD

**Issue by pitchandtone** [tractorcow/silverstripe-fluent#259]
Is anyone working on this or have a plan to and could give some timelines?

**Comment by pitchandtone** [comment]
Or provide a cost? I have a motivated client.

**Comment by tractorcow** [comment]
I plan on upgrading some time closer to beta, where the API will be stabilised and safer to upgrade. Beta is about a month away, but I can't guarantee I'll be able to give fluent module priority though.

**Comment by krv** [comment]
Any updates on this now that the first beta has been released? Thanks for this awesome module btw.

**Comment by tractorcow** [comment]
Thanks for the reminder; Maybe next company friday hackday. :)

**Comment by robbieaverill** [comment]
@pitchandtone @krv FYI there's an RFC up for a new version for SS4 at #261

**Comment by robbieaverill** [comment]
Follow progress with the `affects/v4` label, or #261
