### ISSUE TITLE
Multilanguage Static Link

### ISSUE THREAD

**Issue by digitall-it** [tractorcow/silverstripe-fluent#260]
How to make this code to create a static link Fluent-aware?

```
<% with $Page('booking') %>
<a href="$Link">$MenuTitle</a>
<% end_with %>
```

**Comment by tractorcow** [comment]
Sorry, but the issue tracker isn't really meant to be a place to ask questions. I'll get back to you on this.

In future please email me directly (email is on my profile).

**Comment by tractorcow** [comment]
```
<% with $Page('booking') %>
<a href="$Link">$MenuTitle</a>
<% end_with %>
```

This should be fluent-aware already. If you are in a given locale $Link and $MenuTitle will be localised in the current locale.
