### ISSUE TITLE
LocaleLink

### ISSUE THREAD

**Issue by mmitranic** [tractorcow/silverstripe-fluent#262]
Hello,
In Fluent 3.8, the LocaleLink doesn't take into account the entire current URL, only the current DataObject's URL. For example, if the current URL is "/en/issues/show/80", LocaleLink only returns the "/en/issues" part. It doesn't include the "show/80", which would be the current action and id parameter on the current Page_Controller.

**Comment by tractorcow** [comment]
If you need to build in custom routing parameters into a given link, you will need to override this method in your page class. There is no safe and reliable mechanism to re-inject parameters into a route. Maybe in the future there might be, but realistically fluent will probably leave this up to the developer to implement as necessary. :)
