### ISSUE TITLE
Shift icons to font

### ISSUE THREAD

**Issue by tractorcow** [tractorcow/silverstripe-fluent#274]
https://oblador.github.io/react-native-vector-icons/

For instance this could be used as the main icon for the menu / admin section.

![image](https://user-images.githubusercontent.com/936064/29951222-4dc18182-8f15-11e7-92c6-5a6337813ed2.png)

**Comment by robbieaverill** [comment]
We could also use `font-icon-globe-1` from core, perhaps:

![image](https://user-images.githubusercontent.com/5170590/32424120-603cb592-c30f-11e7-876f-28405cfab032.png)

**Comment by robbieaverill** [comment]
Resolves in #322 - thanks @hdpero!
