### ISSUE TITLE
can't access the support page like configuration page

### ISSUE THREAD

**Issue by matvinculado** [tractorcow/silverstripe-fluent#288]
Hi can't access the support pages like configuration page

please check this one https://github.com/tractorcow/silverstripe-fluent/blob/master/docs/en/configuration.md

Thanks,
Mark

**Comment by tractorcow** [comment]
Sorry, these pages are still being migrated across for master... in the mean time please use
https://github.com/tractorcow/silverstripe-fluent/tree/3/docs/en

Related issue https://github.com/tractorcow/silverstripe-fluent/issues/261
docs is the last un-checked bullet point. :)

**Comment by robbieaverill** [comment]
It's worth mentioning that @tractorcow has done a great job of rewriting the master branch docs for SS4 :)
