### ISSUE TITLE
Overide Write for Certain Languages

### ISSUE THREAD

**Issue by thezenmonkey** [tractorcow/silverstripe-fluent#290]
I need to override the content write for certain fields in my model for certain languages. I'm building a site with multiple English and Multiple German language sites (English: GB/AU/ZA/US and German DE/AT/CH). I'd like to minimize editing for same language but different Region using changes to en_GB and de_DE as master for their other regions.

Would the best way be to extend the FluentExtension and replace the onBeforeWrite and do check there to replicate the content or should I augment the onBeforeWrite directly in my Model?

**Comment by tractorcow** [comment]
Are you using ss4 with the new 4.0.0-alpha1 of fluent, or ss3 and the older (but more stable) version?

**Comment by thezenmonkey** [comment]
I'm still using ss3. 

ss4 isn't going to stable enough before launch :)

**Comment by tractorcow** [comment]
You can put `onBeforeWrite` into your model directly, which will be called before all extensions. You can assign the necessary value to the specific locale-field for each data field. E.g.

```php
public function onBeforeWrite()
{
    // copy record locale (replace with your logic)
    if (Fluent::get_locale() !== 'de_DE') {
        $this->Title_de_DE = $this->Title;
    }
    parent::onBeforeWrite(); // will call fluent write
}
```

**Comment by thezenmonkey** [comment]
Thanks. That's how I'll proceed
