### ISSUE TITLE
On fresh install, no locales have any draft pages

### ISSUE THREAD

**Issue by robbieaverill** [tractorcow/silverstripe-fluent#296]
Steps:

* SS4 vanilla install, require fluent
* Go to admin, create some locales
* Define a fallback chain for some of them
* Refresh page, switch to any locale (default for example)
* Go to Pages and choose a page

Expected result: shows draft version of a page

Actual result: "The requested page could not be found." in the preview panel

---

My fallback chain is en_AU > en_NZ > en_US (global default).

I suppose that with the fallback system, if the default locale doesn't have a record for a page it should fallback to reading from the global SiteTree tables? In this case en_US wouldn't have a home page for example, so would read from the global record instead.

**Comment by tractorcow** [comment]
It's the isFrontend() check on preview that disables the page if it's not published.

My feeling is that the page loaded in preview SHOULD have isFrontend() = false, since it's being loaded in the admin context.

I suggest to add a fix (somehow) to the middleware that sets frontend false in this case.

**Comment by robbieaverill** [comment]
>I suggest to add a fix (somehow) to the middleware that sets frontend false in this case.

Sounds sensible to me!

**Comment by robbieaverill** [comment]
Fix at #305. Was unsure whether it was appropriate or necessary to check the validity of the query string param via either checking for an authenticated session or the referrer being from admin.

**Comment by tractorcow** [comment]
Thanks great fix @robbieaverill !
