### ISSUE TITLE
Add visual UI indicators of some sort to the Pages tree to show fluent status

### ISSUE THREAD

**Issue by robbieaverill** [tractorcow/silverstripe-fluent#297]
![image](https://user-images.githubusercontent.com/5170590/32424282-40938896-c310-11e7-86e7-f54654aff3f2.png)

Given these five pages, some of them may not exist in some locales even in a draft state. In this case we should indicate somehow that they are not available in that locale, perhaps lightening the opacity (keeping contrast for accessibility in mind), e.g.:

![image](https://user-images.githubusercontent.com/5170590/32424315-742c77d0-c310-11e7-8edb-5ee6f1ab4712.png)

We should also indicate draft/modified/published states for pages at each locale.

Currently if I publish a page in the default locale, switch a non-default locale and save a draft of it 
 (say with a new title) then switch back to the default locale (and refresh the page) I see the default locale showing a modified status on the page with the correct original title. In this case the page should be unmodified in the default locale but modified in the other locale.

Correctly showing modified state and page title in non-default locale:
![image](https://user-images.githubusercontent.com/5170590/32424376-eecec33a-c310-11e7-8a03-ac0c560e2520.png)

Incorrectly showing modified state in default locale:
![image](https://user-images.githubusercontent.com/5170590/32424368-dab14e9a-c310-11e7-9554-3ec4626b3b47.png)

Further to this example, if I go to the AU locale (my chain is en_AU > en_NZ > en_US [default]), modify the page title and publish it then it appears to behave correctly, only the page status badges show as published for all locales when NZ has draft changes. Those draft changes still reflect correctly when toggling between draft and published in the preview panel for that locale though.

**Comment by tractorcow** [comment]
Fixed with https://github.com/tractorcow/silverstripe-fluent/pull/301
