### ISSUE TITLE
Changing locales should reload the entire window

### ISSUE THREAD

**Issue by robbieaverill** [tractorcow/silverstripe-fluent#298]
When changing locales via the locale switcher part of the window is reloaded with AJAX. This causes things like the pages tree list not to refresh with, for example, different titles between locales.

If we did a hard page reload this wouldn't be a problem.

**Comment by robbieaverill** [comment]
Fixed in #302

**Comment by tractorcow** [comment]
Well, there is this issue https://github.com/tractorcow/silverstripe-fluent/issues/76 @robbieaverill 

but we can stick with hard-refresh I guess.

**Comment by robbieaverill** [comment]
Interesting. There seems to be a fair bit of support for not doing a hard refresh. Should we revert?

**Comment by tractorcow** [comment]
I think hard refresh is safer. We can always revisit if we need to.
