### ISSUE TITLE
v4 FluentFilteredExtension: Issue with FilteredLocale logic on Pages with their own localisation

### ISSUE THREAD

**Issue by chrispenny** [tractorcow/silverstripe-fluent#307]
When viewing a page that has it's own (published) localisation, we shouldn't require that the same locale is also added into that Page's `FilteredLocales` records.

This is one for me to pick up (please feel free to assign it to me) - I'm just documenting it here so that I don't forget (as I might not be able to look at it today).

**Comment by tractorcow** [comment]
> When viewing a page that has it's own (published) localisation, we shouldn't require that the same locale is also added into that Page's FilteredLocales records.

I think it is logical that it must be added to that mapping, otherwise records that seem hidden in a locale could easily and accidentally be added into that live locale. See my comment on #309
