### ISSUE TITLE
v4 FluentFilteredExtension: Add styles for Site Tree

### ISSUE THREAD

**Issue by chrispenny** [tractorcow/silverstripe-fluent#308]
Another one for me to look at (please feel free to assign this to me).

Add some additional styles so that it is clear which Pages are and are not currently visible as you browse the CMS in any particular Locale.

Something like this (where the "About us" page isn't visible on this current Locale):
<img width="223" alt="screen shot 2017-11-17 at 8 35 40 am" src="https://user-images.githubusercontent.com/505788/32911879-5a0db1ec-cb72-11e7-9d16-2153de99940e.png">

I'd also like to look into how easily I could add similar visibility to things like SiteTree dropdown fields, but that may end up being a further improvement later down the line.

**Comment by tractorcow** [comment]
I thought we implemented this with the original PR https://github.com/tractorcow/silverstripe-fluent/pull/304

**Comment by chrispenny** [comment]
That PR only contained the styles for the "Inherited" and "Locale Drafted" flags. This is a new style to try and illustrate that a Page is not visible on the current Locale.

**Comment by chrispenny** [comment]
@tractorcow I am wondering though:

This `Extension` is not tied to `SiteTree`, it could be applied to any `DataObject`. With that in mind, it feels slightly wrong that I would implement the `updateStatusFlags()` method in this `Extension`.

I would be happy with either of these options:

1. I implement the `updateStatusFlags()` method in this `Extension` for any time it is applied to `SiteTree` (probably quite often?).
2. We leave it to devs to write their own `Extension` which can make all of the correct assumptions about the `DataObject` that this `Extension` has been applied to.

**Comment by tractorcow** [comment]
I think 1. is ok; Just document that `updateStatusFlags` is only intended for cases where this extension is added to SiteTree, and that it can be ignored all other times.
