### ISSUE TITLE
adding a locale using cms results in error

### ISSUE THREAD

**Issue by guyvanbael** [tractorcow/silverstripe-fluent#312]
Configuring a locale in the cms results in internal server error. The locale is added, but you get the error and editing isn't possible anymore.
![schermafbeelding 2017-11-29 om 11 21 44](https://user-images.githubusercontent.com/3098809/33378146-33afa590-d514-11e7-859e-191e7a20e255.png)

**Comment by tractorcow** [comment]
Can you please ensure your CMS environment is set to dev and please post the error message from the HTTP response?

**Comment by muaddibus** [comment]
It throws: 
[2018-01-05 10:38:33] error-log.ERROR: Uncaught Exception Exception: "Inline adding requires the editable columns component" at site_root/gridfieldexte
nsions/src/GridFieldAddNewInlineButton.php line 90 {"exception":"[object] (Exception(code: 0): Inline adding requires the editable columns component at site_root/gridfieldextensions/src/GridFieldAddNewInlineButton.php:90)"} []

Composer.json:
        "tractorcow/silverstripe-fluent": "^4",
        "symbiote/silverstripe-gridfieldextensions": "^3@dev"

**Comment by tractorcow** [comment]
Possibly related to #318. Solution may be a 3.0.3 tag on gridfieldextensions.

**Comment by tractorcow** [comment]
@guyvanbael since https://github.com/tractorcow/silverstripe-fluent/pull/320 has been merged can you please check if an update fixes your site?

Please make sure you are using beta2 https://github.com/tractorcow/silverstripe-fluent/releases/tag/4.0.0-beta2

**Comment by guyvanbael** [comment]
@tractorcow Doing a composer update fixed the problem.
