### ISSUE TITLE
500 Internal Error on already created language

### ISSUE THREAD

**Issue by HACKHERS** [tractorcow/silverstripe-fluent#315]
Hello, I used fluent in my dev server without any problem. But when I move the files to live server, and the database my languages stopped working. When I use FluentValidateTask it says: Fluent config is valid!

I have 2 languages in my database, and they are: en_US, tr_TR. But tr_TR part isn't working at all. /admin/pages?l=tr_TR returns 500 without any error messages. I don't know what to do

**Comment by robbieaverill** [comment]
Hey @HACKHERS, thanks for the report - can you please provide your SilverStripe and Fluent versions?

**Comment by HACKHERS** [comment]
I tried to move all of my files to live server and the database. I moved them to the same folder just to be sure. Site totally unreachable right now, I can give the access info if one of the collaborators wants to examine the issue.

**Comment by tractorcow** [comment]
@HACKHERS I think the problem is that you have a manifest issue; If you install with composer, what will happen is that composer will build a class map of all CMS classes and interfaces, meaning such errors won't occur.

The relevant part is in `cms/composer.json`

```json
"autoload": {
    "classmap": ["tests/behat/", "code"]
}
```

You can try running `composer dump-autoload` in your web root... that might help get it working?

**Comment by tractorcow** [comment]
cms 3.6.3 is coming out today; Maybe hold tight and see if that fixes it. :)

**Comment by tractorcow** [comment]
It's out :D

**Comment by intwebg** [comment]
I have the same problem with version 3.6.5 of Silverstripe and Fluent 3.8

**Comment by tractorcow** [comment]
Oh no! Can you confirm it's the same bug? `Fatal error: Interface 'CurrentPageIdentifier' not found in `?

**Comment by intwebg** [comment]
I've responding for the main topic « 500 Internal Error on already created language » from  @HACKHERS. I can help there Ive done some testing and there is the solution : I have installed a fresh copy of Silverstripe 3.6.5 WITH Composer and with ALL modules that I've used. It **WORKS** now. Very strange bug. Why it's not working on downloaded installation but It do with Composer installation...

**Comment by robbieaverill** [comment]
Thanks for clarifying that this works when installing with Composer. We always recommend using Composer where possible, and require it in SilverStripe 4
