### ISSUE TITLE
Error :these conflict with your requirements or minimum-stability

### ISSUE THREAD

**Issue by anupriya24july** [tractorcow/silverstripe-fluent#317]
"Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package tractorcow/silverstripe-fluent ^4 is satisfiable by tractorcow/silverstripe-fluent[4.0.0-alpha1, 4.0.x-dev] but these conflict with your requirements or minimum-stability."
 
I am getting this error when trying to install. I am using silverstripe 4 and php 7.1.12

**Comment by robbieaverill** [comment]
Hi @anupriya24july, can you please share your `composer.json` file contents?

It's likely that you'll need to add the following to your `composer.json` to allow composer to install unstable packages:

```
    "minimum-stability": "dev",
    "prefer-stable": true
```

**Comment by anupriya24july** [comment]
{
    "name": "silverstripe/installer",
    "type": "silverstripe-recipe",
    "description": "The SilverStripe Framework Installer",
    "require": {
        "php": ">=5.6.0",
        "silverstripe/recipe-plugin": "1",
        "silverstripe/recipe-cms": "1.0",
        "stevie-mayhew/silverstripe-svg": "^2.0",
        "heyday/silverstripe-hashpath": "^3.0.0",
        "silverstripe/googlesitemaps": "^1.8.0",
        "eo/passbook": "^2.0.0",
        "kinglozzer/metatitle": "^2.0.3",
        "omnipay/paymentexpress": "^2.2",
        "mobiledetect/mobiledetectlib": "~2.8.22",
    },
    "require-dev": {
        "phpunit/PHPUnit": "^5.7"
    },
    "extra": {
        "project-files": [
            "assets/*",
            "mysite/_config/*",
            ".env.example",
            "favicon.ico"
        ],
        "project-files-installed": [
            ".htaccess",
            "index.php",
            "install-frameworkmissing.html",
            "install.php",
            "mysite/.htaccess",
            "mysite/_config.php",
            "mysite/_config/mysite.yml",
            "mysite/code/Page.php",
            "mysite/code/PageController.php",
            "web.config"
        ]
    },
    "config": {
        "process-timeout": 600
    },
    
    "prefer-stable": true
}
 this is my json file. I did try with the "minimum-stability": "dev" that you suggested but no luck. the same error persist.

**Comment by tractorcow** [comment]
I've since tagged 4.0.0-beta1. I've noticed this isn't in your list of suggested versions.

```
- The requested package tractorcow/silverstripe-fluent ^4 is satisfiable by tractorcow/silverstripe-fluent[4.0.0-alpha1, 4.0.x-dev] but these conflict with your requirements or minimum-stability."
```

I would suggest you change your requirements to use `^` or `~` operator. I think the recipe-plugin you have there is fixed at `"1"` which isn't a real version in itself.


```diff
"require": {
        "php": ">=5.6.0",
-        "silverstripe/recipe-plugin": "1",
+        "silverstripe/recipe-plugin": "^1",
-        "silverstripe/recipe-cms": "1.0",
+        "silverstripe/recipe-cms": "~1.0.0",
        "stevie-mayhew/silverstripe-svg": "^2.0",
        "heyday/silverstripe-hashpath": "^3.0.0",
        "silverstripe/googlesitemaps": "^1.8.0",
        "eo/passbook": "^2.0.0",
        "kinglozzer/metatitle": "^2.0.3",
        "omnipay/paymentexpress": "^2.2",
        "mobiledetect/mobiledetectlib": "~2.8.22",
    },
```

**Comment by dhensby** [comment]
@anupriya24july you don't have a `"minimum-stability": "dev"` in your `composer.json` which means non-dev releases (eg: alpha tags, beta tags, RC tags, nor dev branches will be matched)
