### ISSUE TITLE
v4: Locale::getCMSFields() doesn't implement extend('updateCMSFields')

### ISSUE THREAD

**Issue by chrispenny** [tractorcow/silverstripe-fluent#325]
I can probably sort this on hackday this Friday if you want to assign to me.

**Question though:**
Is there a particular reason why `Locale::getCMSFields()` explicitly creates a new `TabSet` rather than just calling `parent::getCMSFields()`?

IE, this:
```php
$fields = FieldList::create(TabSet::create('Root'));
```
Rather than this:
```php
$fields = parent::getCMSFields();
```

**Comment by robbieaverill** [comment]
Unless @tractorcow has a reason to create a new FieldList explicitly, I think it makes sense to switch it to using `parent::getCMSFields`

**Comment by tractorcow** [comment]
The default scaffolder is awful that's why :)

**Comment by tractorcow** [comment]
Fixed with https://github.com/tractorcow/silverstripe-fluent/pull/326
