### ISSUE TITLE
Using Fluent with i18n lang files (lang/{lang}.yml)

### ISSUE THREAD

**Issue by blueskies79** [tractorcow/silverstripe-fluent#327]
First off: thanks for the wonderful work with this module!

Then for the issue I ran into: I have an SS4 site which needs to be multilingual, though not all text is maintained by the CMS. So I also require i18n translation files to be able to add simple text to templates (like the <%t AboutUsPage.EmailUs "Send us an email" %> format). For this we use the https://docs.silverstripe.org/en/4/developer_guides/i18n/ which allows a series languages in the lang folder to pick up the translations (nl.yml, fr.yml, en.yml, etc). The i18n setup was followed and we noticed that the i18n was always defaulting to en.yml, even though Fluent was properly installed and language switching (through the <% include LocaleMenu %>) was working fine for the cms-content. Dumping $Locale and $CurrentLocale in the template showed that it was switching properly according to whichever language Fluent was switched to, but i18n was simply not aware of the switched locales and kept picking up the en.yml.  

We fixed the issue by adding this line: i18n::set_locale(FluentState::singleton()->getLocale()); to the init() of the PageController. But I'm wondering if Fluent's locale should be sent to i18n by the module rather than be explicitly set like that?

**Comment by tractorcow** [comment]
Yes I think it needs to do this; We can fix by adding that to the middleware.
