### ISSUE TITLE
alternate language not working in ss4.0.1

### ISSUE THREAD

**Issue by guyvanbael** [tractorcow/silverstripe-fluent#332]
Using ss4.0.1 the template which adds the alternate language isn't used. The default from googlesitemaps module is used. Copying the code over to the googlesitemaps template is a workaround.

**Comment by tractorcow** [comment]
Oh right, I hadn't updated with the latest googlesitemaps templates;

https://github.com/wilr/silverstripe-googlesitemaps shows that's it's been updated; We can fix by setting the correct template name :D

**Comment by robbieaverill** [comment]
@guyvanbael would you be keen to submit a pull request to fix this?

**Comment by guyvanbael** [comment]
@robbieaverill haven't done pull requests yet, but i'd happy to try. What i did in my project however, what i did in my project, was copy your extra's in the template over to the googlesitemap template, because that's the one that was being rendered. If you can point me to the file where it's set in the fluent module. I'll try to fix it the proper way and send you a PR.

**Comment by tractorcow** [comment]
It'll be in the same folder; `templates/Wilr/GoogleSitemaps/Control` but in the fluent module.

**Comment by guyvanbael** [comment]
@robbieaverill i found `FluentSitemapController_sitemap.ss` but it's still the one in `templates/Wilr/GoogleSitemaps/Control` that gets rendered.

**Comment by robbieaverill** [comment]
@guyvanbael you’ll need to move the template so it matches the same folder structure as the template you want to override

**Comment by guyvanbael** [comment]
@robbieaverill Do you mean i have to recreate that folder structure in the fluent module?

**Comment by robbieaverill** [comment]
Yep!

**Comment by guyvanbael** [comment]
allright... i'll fix it later today

**Comment by guyvanbael** [comment]
@robbieaverill i made a PR... hope i did ok :-)

**Comment by tractorcow** [comment]
Close. Some feedback left on https://github.com/tractorcow/silverstripe-fluent/pull/336
