### ISSUE TITLE
Fluent SiteTree labels overlay CMS labels

### ISSUE THREAD

**Issue by robbieaverill** [tractorcow/silverstripe-fluent#334]
![image](https://user-images.githubusercontent.com/5170590/35412334-be861976-0280-11e8-86b3-664fec77bcac.png)

**Comment by tractorcow** [comment]
@chrispenny do you want to have a look at this? Do you know how you avoided this clash when you added in the page status?

**Comment by chrispenny** [comment]
@tractorcow I didn't avoid it, unfortunately. I thought I had raised an issue about this on the CMS repo, but I guess I didn't (sorry).

I'm not sure that this is a uniquely Fluent issue - it happens any time there is more than one valid status flag on a record. Embargo & expiry comes to mind as another time where there might be (for example) an (ootb) "modified" flag, and an (e&e) "expiry" flag set at the same time.

**Comment by raissanorth** [comment]
I recreated this issue and had a quick peak into the styling of the badges. 

It appears that they are all positioned absolute with a zero margin to the right. So they are bound to overlap. Even if we were to spread them out, it could get cluttered really fast:

![image](https://user-images.githubusercontent.com/14869519/36010979-17c92b84-0db9-11e8-8194-afa9768035d8.png)

Perhaps we should reconsider how to display the way we show inherited locales and leave the use of badges to the CMS module to show the modified status of pages?

**Comment by sachajudd** [comment]
cc @clarkepaul

**Comment by chrispenny** [comment]
@raissanorth (CC: @sachajudd), other modules also make use of these status flags (EG: [Advanced workflow](https://github.com/symbiote/silverstripe-advancedworkflow/blob/master/src/Extensions/WorkflowEmbargoExpiryExtension.php#L358)), so I feel that this is far more wide reaching than just Fluent.

If we were to decide that status flags are only meant to be used by the CMS module, then these extension points should be removed (or repurposed), and we'll need a new way to expose this sort of information to the user.

**Comment by robbieaverill** [comment]
This may potentially be a wider reaching issue.

I've spoken to @clarkepaul about this today, and we both thought that if we remove the Fluent sitetree labels, we can move communicating that information to the edit screen of the page itself in the form of new labels and/or alert messages there instead.

We'd still keep the darker page titles for pages that are not visible (on the frontend) in the current locale, so the colour of the page title in the sitetree would then represent whether the page is visible for frontend users in the current locale or not. Note: if using inheriting fallback locales, we might need to change the existing logic to show inherited (and visible) pages are shown in default blue rather than darker.

There are some designs coming to compliment the removal of sitetree labels in the CMS edit form shortly, in the various situations e.g. locales inheriting versus locales are exclusive, and whether the content exists in the current locale or is inherited/copyable from.

We need to document the crap out of this too =D

**Comment by clarkepaul** [comment]
Mockups for what @robbieaverill has discussed above here. https://invis.io/ZBFVZJCKU38#/279729292_X_Fluent

**Comment by chrispenny** [comment]
@clarkepaul that looks super good. Love it.
