### ISSUE TITLE
fluent breaks fulltextsearch

### ISSUE THREAD

**Issue by guyvanbael** [tractorcow/silverstripe-fluent#335]
configuring basic site search (by enabling fulltextsearchable) doesn't work when fluent module is 
installed. Here's the stack strace.
https://gist.github.com/guyvanbael/d23c189dbcc181bc50c377d6a38aac7f

**Comment by tractorcow** [comment]
Ah yeah, fulltextsearch is pretty bad. It'll be a bit of a mission to support it.

We may need to add a custom search engine query builder just for fluent.

**Comment by robbieaverill** [comment]
I'll make this into a ticket to ensure we have something that connects Fluent and FTS in a usable way
