### ISSUE TITLE
Question about fluent locale

### ISSUE THREAD

**Issue by ijokerassassin** [tractorcow/silverstripe-fluent#342]
Hey there, 

Currently Im using fluent and it is working great, but I got stuck on a little thing. I want to update some database fields with a cronjob but to do that I need to set locale in the controller to update the country 
dependent fields. Is this possible in the current fluent?

Kind regardes

**Comment by robbieaverill** [comment]
Hi there, I’m not sure which version you’re using but in SS3 you can use `Fluent::with_locale` and in SS4 it’s `FluentState::singleton()->withLocale()`

**Comment by ijokerassassin** [comment]
What does fluent except in the callback?

**Comment by tractorcow** [comment]
A closure that handles any database writes you want.

**Comment by bhofstaetter** [comment]
Could it be that it isn't implemented yet for SS4?

**Comment by robbieaverill** [comment]
@bhofstaetter you can achieve this as mentioned above:

```php
FluentState::singleton()->withState(function (FluentState $newState) {
    // Set the locale you want to modify data in here
    $newState->setLocale('en_AU');

    $page = SiteTree::get()->filter('ID', 123);
    $page->Content = 'Australian content only';
    $page->write();
});
```

Hope this helps!

**Comment by robbieaverill** [comment]
No problem, happy translating!
