### ISSUE TITLE
UX Fluent and language indicator icons not displayed nicely when screen width is narrow

### ISSUE THREAD

**Issue by raissanorth** [tractorcow/silverstripe-fluent#347]
When using the CMS in split mode and with a narrow screen width the Fluent icons and language indicator icons get smooshed with the field titles. See screenshot below:

![image](https://user-images.githubusercontent.com/14869519/36002501-44667892-0d8f-11e8-8ab4-933739178c0c.png)

**Comment by robbieaverill** [comment]
This is related to #343 which isn't merged yet - hold for now!

**Comment by raissanorth** [comment]
Indeed #343 has been closed without being merged. 

In the feedback @clarkepaul suggested the following UX changes https://projects.invisionapp.com/share/ZBFVZJCKU38#/screens/279729292_X_Fluent to indicate the locale instead. 

I am closing this issue as it is not relevant any longer.
