### ISSUE TITLE
Editing a non-default local affects the default locale

### ISSUE THREAD

**Issue by NightJar** [tractorcow/silverstripe-fluent#349]
While editing the Home page of my site in the "German" `locale` (where the default is "English (New Zealand)") I changed the title to "Home, lang:de", then clicked "Save and Publish".

This correctly updated `SiteTree_localised_live` to reflect the change `where Locale = 'de'`, however to my surprise then viewing the `SiteTree_live` table also revealed that `Title = 'Home, lang:de'`, which is somewhat both an erroneous state, and technically false.

This issue however did _not_ occur when editing the Content of the same page.

`tractorcow/silverstripe-fluent: 4.0.x-dev`
`commit ddf8c127328bb5d1f506a5e4b5b1bfdb99ebd1e9 (HEAD -> master, origin/master, origin/HEAD, composer/master)`

**Comment by robbieaverill** [comment]
Can you provide a screenshot of your locale configuration please

**Comment by NightJar** [comment]
![capture](https://user-images.githubusercontent.com/778003/36187721-0ab0b48e-11ac-11e8-8ed0-9d0a98334e10.PNG)
Neither have `Domains` set (and none exist on that tab).

**Comment by robbieaverill** [comment]
Does German fall back to English or are they isolated?

**Comment by robbieaverill** [comment]
>This correctly updated SiteTree_localised_live to reflect the change where Locale = 'de', however to my surprise then viewing the SiteTree_live table also revealed that Title = 'Home, lang:de', which is somewhat both an erroneous state, and technically false.

I believe this is expected behaviour, since Fluent will be reading from SiteTree_Localised_Live for all locales (including the default)

**Comment by NightJar** [comment]
Again some 'unclarity' on my part on how Fluent does it's things in v5.
The locales weren't set up with any fallbacks (that I know of, i.e. unless it's automatically assumed).

However having talked with @tractorcow about this...

I had assumed the SiteTree(_live) table was still used for the selected _default_ locale.
However this is not the case. The 'parent' or 'root' table is only used for non-translated fields. Title is translated, meaning that the field on SiteTree is effectively not used anymore; so this update doesn't matter.
