### ISSUE TITLE
Installing fluent causes the default locale/site to disappear.

### ISSUE THREAD

**Issue by NightJar** [tractorcow/silverstripe-fluent#350]
After installing fluent and setting up 2 locales:
- en_NZ (default: true)
- de_DE

the main site (`localhost/`) has disappeared. Furthermore I cannot get `localhost/about-us` nor `localhost/en_NZ/about-us` to load.
`localhost/de_DE` however loads, although it shows as the only page available (no other translations have been made for other pages, so I assume this is correct).

I may have something misconfigured - in which case the issue is less severe, but could end up being a common pitfall.

`tractorcow/silverstripe-fluent: 4.0.x-dev`
`commit ddf8c127328bb5d1f506a5e4b5b1bfdb99ebd1e9 (HEAD -> master, origin/master, origin/HEAD, composer/master)`

**Comment by robbieaverill** [comment]
Yeah you need to publish those pages in each locale you want them to be visible in. We should make it easier if we can, to ensure the default 5 pages that you get when you install SilverStripe are available in the default locale at least

**Comment by NightJar** [comment]
So this is a misunderstanding on my behalf. Fluent currently requires _all_ locales to be set up and published - the site as it was before installation is effectively a non-thing once a locale is created.

I'll expand on this description later :>

**Comment by robbieaverill** [comment]
We could maybe also add a task that would publish all pages in the default locale
