### ISSUE TITLE
Select Locale dropdown in the CMS has... issues.

### ISSUE THREAD

**Issue by NightJar** [tractorcow/silverstripe-fluent#351]
Selecting a language to edit in the CMS has a number of usability problems:

- It does not (dis)appear/update when (deleting/)adding/editing a `Locale`
- It is not accessible for persons with _and without_ eyesight issues (see image)
- It stops functioning when the sidebar is collapsed (perhaps in other states too, not fully tested)

![capture](https://user-images.githubusercontent.com/778003/36187566-f7c911a0-11aa-11e8-8fcf-f700f6d9097b.PNG)
The other locale in this is screen capture is "German (Germany)"
Soon afterward the dropdown ceased to function at all.

`tractorcow/silverstripe-fluent: 4.0.x-dev`
`commit ddf8c127328bb5d1f506a5e4b5b1bfdb99ebd1e9 (HEAD -> master, origin/master, origin/HEAD, composer/master)`

**Comment by robbieaverill** [comment]
> It does not (dis)appear/update when (deleting/)adding/editing a Locale

See #337 

>It is not accessible for persons with and without eyesight issues (see image)

Can you please elaborate on what you mean here? We're using Bootstrap components, so provided we add the correct aria attributes we should have our base covered with accessibility

>It stops functioning when the sidebar is collapsed (perhaps in other states too, not fully tested)

Can you please provide your browser version? It works fine for me on MacOS with Chrome 63:

![image](https://user-images.githubusercontent.com/5170590/36188895-2660f998-11b4-11e8-8628-1ac829c269c0.png)

Re-labelling as impact/medium: "Unexpected behaviour but does not break functionality"

**Comment by NightJar** [comment]
Hmm, truth it probably is accessible to those with sight impairment (screen readers & whatnot), however having the CSS properties `colour` == `background-colour` make it impossible to view any option except the highlighted one (which is white on blue).

From your screenshot it would appear that the difference in MacOS chrome is that it uses some sort of system rendered dropdown, where as I use Windows (also Chrome, 64.0) draws what I thought was a javascript component, however on closer inspection appears that Chrome permits the styling of the `<select>` and `<options>` on Windows (where as it seems MacOS does not). I'm also now about 80% sure Chrome updated when I opened it this morning (after my computer shut down overnight) as everything is **_fine_** this morning -.-

Maybe it was Chrome 63 on Windows, specifically. Maybe the computer was out of memory and couldn't handle rendering text colour. I dunno. Works now, so I'll close.

**Comment by robbieaverill** [comment]
Ok good to know. We can re-open if you notice it again

**Comment by NightJar** [comment]
I can reproduce this :)
The issue manifests when the sidebar is collapsed (icon only, as per screenshot).
When the sidebar is full width (ie. 'normal' - icon & text too) the issue does not occur.
I find this rather bizarre, and I've not had time to investigate. But it's worth reopening to keep track of.

* The issue is windows only
* only when using the CMS main menu in 'icon only' mode.

**Comment by robbieaverill** [comment]
Potential solution noted in #392

**Comment by JorisDebonnet** [comment]
I'll have a go at it

**Comment by NightJar** [comment]
@JorisDebonnet I've found that using `yarn build` fails as you describe, but running the items directly instead of relying on the path sees success.

https://github.com/tractorcow/silverstripe-fluent/blob/master/package.json#L9

`NODE_ENV=production webpack -p --bail --progress` becomes `NODE_ENV=production node_modules/.bin/webpack -p --bail --progress`
(of course if you're not using a bash shell the environment var will also give you a hard time, but I think that omitting it sees the same results, as it switches on NODE_ENV=development and assumes production as default ... I _think_).

**Comment by JorisDebonnet** [comment]
Finally got it to work by making sure I used yarn (not npm) and then manually executed `NODE_ENV=production webpack -p --bail --progress` from Git bash. I guess `yarn build` runs outside bash or something, causing issues. 
I then kept worrying that the fluent.css.map did not update correctly, or if it did, included my personal local paths; so I eventually just didn't commit that one. Bleh node_modules :P

**Comment by NightJar** [comment]
Yeah, I don't have webpack installed globally, so I run from node modules, otherwise that seems equivalent :)
I'm not sure that the production build does create a map file (pretty sure it doesn't). But you can change the command to look more like the one for the build dev or whatever it is to ensure one is generated.
