### ISSUE TITLE
Deleting a record removes the entire table.

### ISSUE THREAD

**Issue by ailionx** [tractorcow/silverstripe-fluent#354]
https://github.com/tractorcow/silverstripe-fluent/blob/8e863f0de9d455bdfea5ce71471a41362940f7c8/src/Extension/FluentExtension.php#L433

This seems deletes the whole table while it's supposed to delete only one record?

**Comment by NightJar** [comment]
Hi @ailionx - thanks for your accompanying pull request to help resolve this issue :)
In future could you please also describe the steps you're performing to envoke this issue?
It would also be nice if you could quickly discuss what you expected, and what you actually saw happen. Even though this change seems somewhat trivial, it greatly helps people get up to speed with what you'd attempting to fix, and understand _why_.
