### ISSUE TITLE
Bulk-actions on SiteTree items do not work

### ISSUE THREAD

**Issue by JorisDebonnet** [tractorcow/silverstripe-fluent#379]
The offending query includes the following: 
`... AND "SiteTree_Localised_en_US"."Locale" = ? AND "SiteTree_Localised_en_US"."Version" = "SiteTree_Versions"."Version"  WHERE ("RecordID" IN (?, ?)) ...` 
(if I selected two pages to (un)publish, otherwise of course more ?)

Resulting in: `Column 'RecordID' in where clause is ambiguous`

This happens when I try to bulk-publish or bulk-unpublish in SilverStripe 4.1.0 with Fluent 4.0.0.

**Comment by robbieaverill** [comment]
I'm pretty sure this is fixed with https://github.com/silverstripe/silverstripe-admin/pull/581 (available in the next core patch release). If that doesn't resolve this problem then feel free to reopen the issue.
