### ISSUE TITLE
Locale options in dropdown invisible when cms-menu is collapsed

### ISSUE THREAD

**Issue by JorisDebonnet** [tractorcow/silverstripe-fluent#392]
This is in Firefox: 
![image](https://user-images.githubusercontent.com/3286264/38530753-89d6349c-3c6c-11e8-93d0-cd7a5304e4d7.png)

It can be easily solved: in `fluent.scss` around row 80 add `> option {color:white}`. I haven't created a pull request because I'm not sure how to get the `src` to compile to `dist`.

**Comment by robbieaverill** [comment]
@JorisDebonnet to compile the frontend assets you'll need npm and/or yarn, then you can run `npm install && npm run build` or `yarn && yarn build`

**Comment by robbieaverill** [comment]
Duplicate of #351
