### ISSUE TITLE
Composer requirement not found

### ISSUE THREAD

**Issue by g4b0** [tractorcow/silverstripe-fluent#401]
Trying to update via composer I get the following error:

```
Problem 1                                                                                                                      
      - Installation request for tractorcow/silverstripe-fluent dev-master -> satisfiable by tractorcow/silverstripe-fluent[dev-master].                                                                                                                          
      - tractorcow/silverstripe-fluent dev-master requires symbiote/silverstripe-gridfieldextensions ^3.0.3 -> no matching package found.
```

symbiote/silverstripe-gridfieldextensions 3.0.3 does not exist

**Comment by dhensby** [comment]
What does your `composer.json` look like? do you have `"minimum-stability": "dev"`?

**Comment by robbieaverill** [comment]
True that 3.0.3 doesn't exist. I'll lower this constraint a little =)

**Comment by g4b0** [comment]
I still have problems updating:
```
 Problem 1                                                                                                                             
      - Installation request for tractorcow/silverstripe-fluent dev-master -> satisfiable by tractorcow/silverstripe-fluent[dev-master].  
      - tractorcow/silverstripe-fluent dev-master requires symbiote/silverstripe-gridfieldextensions ^3.0 -> no matching package found.
```

My composer.json looks like:

```
    "require": {
        "php": ">=5.6.0",
        "silverstripe/recipe-plugin": "^1",
        "silverstripe/recipe-cms": "1.1.0@stable",
        "silverstripe-themes/simple": "~3.2.0",
        "tractorcow/silverstripe-fluent": "dev-master",
        "symbiote/silverstripe-gridfieldextensions": "dev-master",
        "g4b0/simple-gallery": "dev-master"
    },
```

**Comment by dhensby** [comment]
@g4b0 that looks like only a selection of the `composer.json` and not all of it. Can you provide all of it.

Also, I'd recommend you do not use `dev-master` as a constraint *ever*. I'm also confused that you've got `"symbiote/silverstripe-gridfieldextensions": "dev-master"` when the failure is to install 3.0... Something funky is going on in general.

**Comment by g4b0** [comment]
Wow, changing my composer json with 

"symbiote/silverstripe-gridfieldextensions": "^3.0"

did the trick!

**Comment by dhensby** [comment]
Yep, you need to stop using `dev-master` or you're going to be in a world of pain

**Comment by g4b0** [comment]
Like the good old days of SS 3.0-dev :)
Thanks a lot
