### ISSUE TITLE
frontend_publish_required not working as expected

### ISSUE THREAD

**Issue by derralf** [tractorcow/silverstripe-fluent#406]
in my fluentconfig.yml I've set
```
Derralf\App\Model\TeaserBox:
  frontend_publish_required: false
```
TeaserBox is not versioned. 
Global default locale is en_US
SS 4.1 with Fluent ^4

If I understand correctly, with `frontend_publish_required` set to `false` my english (not yet translated) TeaserBoxes should display on my german and italian Pages as well with fallback contents.
But it will only display after localising it (open & save on german/italian page or modeladmin).

Only setting `frontend_publish_required` to false globally:
```
TractorCow\Fluent\Extension\FluentExtension:
  frontend_publish_required: false
```
...will display my non-localised teasers in the frontend, but will also affect Sitetree and all other fluent-extended Objects as well.

What am I doing wrong?
What did I miss?

**Comment by tractorcow** [comment]
No you've run into a typical config use case... we've discovered that extensions configs override yml configs. We need to remove the config from the yml, and invert it. (frontend_publish_not_required) or something to that effect.

**Comment by tractorcow** [comment]
Discussion at https://github.com/silverstripe/silverstripe-framework/pull/7971

**Comment by tractorcow** [comment]
Fix at https://github.com/tractorcow/silverstripe-fluent/pull/407 by providing another filter you can use.

**Comment by derralf** [comment]
will these changes be released anytime soon? (e.g. in 4.0.3)
or do have i to use `@dev`

**Comment by robbieaverill** [comment]
Seems reasonable to get this fix out now, I'll release a new (minor) version shortly
