### ISSUE TITLE
Unicode characters as Locale URLSegments

### ISSUE THREAD

**Issue by frankmullenger** [tractorcow/silverstripe-fluent#421]
Issue where we need to use special characters for URL segments of Locales e.g: french locale uses `nouvelle-zélande`.

The problem is, this string is URL encoded in `$_SERVER[REQUEST_URI]` and that value is used to try and match a rule which has the decoded string basically.

It seems to work if we add encoded rules here for instance: 
https://github.com/tractorcow/silverstripe-fluent/blob/master/src/Extension/FluentDirectorExtension.php#L118
```php
$rules[urlencode($url) . '/$URLSegment!//$Action/$ID/$OtherID'] = [
                'Controller' => $controller,
                $queryParam => $locale,
];
// and the home URL route converted in a similar way...
```

**Comment by robbieaverill** [comment]
Fixed with #437
