### ISSUE TITLE
Fluent not creating columns within DataObject SS3

### ISSUE THREAD

**Issue by liamchowneydev** [tractorcow/silverstripe-fluent#425]
I have a glossary page that has many glossary items
my fluent.yml looks like this is attatched within the zipped folder.

my glossary items looks like this
     
    `class GlossaryItems extends DataObject {

    private static $db = array(
        "KeyWord"       => "Text",
        "Description"   => "Text",
    );

    private static $has_one = array(
        "GlossaryPage" => "GlossaryPage"
    );

    private static $translate = array(
        'KeyWord',
        'Description',
    );

     }`

The above works perfectly fine BUT I have the exact same scenario with ContentTemplateOne.php which has many ImageCaptions and I get this error. (see image attatched)

How can a class have the same fluent.yml definitions and class structor but flag up an error? I have spent 6-8 hours debuging this ranging from renaming classes, starting again with new classes, starting the project again by reverting the database to its original stage before any errors started. 
When I check the database the columns are not being created in association with the locales but they are created on glossary items class that works.

Is this a module bug or have I done something wrong???

 Please see attatched the a folder of the 3 files that cause the error. (class,dataobject and fluent.yml
[git.zip](https://github.com/tractorcow/silverstripe-fluent/files/2090866/git.zip)

``
![error](https://user-images.githubusercontent.com/40177373/41244054-d6ef4a4c-6d9b-11e8-9b02-a73f7629db40.PNG)

**Comment by bummzack** [comment]
Your `fluent.yml` is malformed. You can't have new configurations in the middle of the `Fluent:` config section. Eg. this part:
```
## Data objects to be translated
GlossaryItems:
  extensions:
    - FluentExtension
ImageAndCaption:
  extensions:
    - FluentExtension
```

Should be at the end of the file, otherwise the following configuration (`data_include`, `field_exclude`, etc.) will belong to `ImageAndCaption`, not `Fluent`.

Not sure if this fixes your issue though.
