### ISSUE TITLE
From secarios documentation: Solution two - Require localisation or Fallback localisation errors

### ISSUE THREAD

**Issue by micahsheets** [tractorcow/silverstripe-fluent#432]
I want to use Solution Two so that any pages that have not been published in a locale are not visible on the front end. However the instructions provided in the docs are insufficient and contain errors. For example FluentHelper::getDataQueryLocale($dataQuery). FluentHelper does not seem to be a class in the Fluent ^4. also is SiteTreeFluentExtension extends SiteTreeExtension correct and what classes do I apply this extension to?

I also want to be able to only show language options in the language switcher for which there are actual translations published. So if there are no translations other than the default, there would not be a language switcher.

I also want to know if there is a way to attache different many_many and has_many relationships to different translations of a page or object. I would rather attache different objects then have to make all the relation objects translatable.

I am trying to find out ways to make Fluent pretty much work just like the Translatable module as it is not available for SS 4 and may not every be.

Thanks for any info.

Micah Sheets

**Comment by robbieaverill** [comment]
Hi @micahsheets, the GitHub issue tracker is reserved for reporting bugs in the code. This sounds more like a question, which would be more suitable for forum.silverstripe.org. Best of luck, and thanks for choosing Fluent!
