### ISSUE TITLE
3.2 compatibility

### ISSUE THREAD

**Issue by chillu** [tractorcow/silverstripe-fluent#92]
We should start testing important modules against SilverStripe core master, to ensure a smooth adoption while we transition into the 3.2 release line.

**Comment by wernerkrauss** [comment]
bump. Now that 3.2 is officially released... Any info if fluent already runs on 3.2

**Comment by robbieaverill** [comment]
Seems OK for me running 3.3.1, however I haven't tested that thoroughly yet.

**Comment by tractorcow** [comment]
Yes it seems fine, and we are running CI against 3.2.
