### ISSUE TITLE
VirtualPages MenuTiltle 

### ISSUE THREAD

**Issue by oetiker** [tractorcow/silverstripe-fluent#93]
When working with VirtualPages, it seem that the MenuTitle and MenuTitle_DefaultLanguage do not get updated when working on the default language version of the site.

When switching to any other language and then saveing the VirtualPage the MenuTitle and MenuTitle_DeafultLanguage do get update.

The other Language versions of  the MenuTitle property do get updated in any case.

jut to be sure, I updated to dev-master using composer, but this does not seem to change anything.
- Updating tractorcow/silverstripe-fluent (3.1.x-dev a9c5c41 => dev-master c83ed9c)

**Comment by tractorcow** [comment]
VirtualPages have been changed on 4.x, and once we update fluent for 4.x it should work better.

**Comment by oetiker** [comment]
the future is bright ... will try to console my users with that

**Comment by tractorcow** [comment]
I guess I can't close this until fluent supports 4.x... hah.

**Comment by robbieaverill** [comment]
Fluent supports 4.x, closing =)
