### ISSUE TITLE
Site tree not updating titles

### ISSUE THREAD

**Issue by edead** [tractorcow/silverstripe-fluent#94]
Hello, I have one problem with this otherwise great module. When locale is changed in the back-end, page titles in the Tree View don't update. This would be OK (they never update in Multilingual module, for instance) but if I reload the admin page, they do update to current locale. Moreover, the title of a saved page also updates, which results in the Tree View showing titles in mixed languages. Do I make any sense?

What I mean is, for example:
1. Locale is Polish. Tree View shows pages in Polish. OK.
2. Switch to English. Tree View still shows pages in Polish, although upon clicking them I can properly edit English data.
3. Edit some page and save it. Now it updates and shows in the Tree View in English, while other pages in the tree still show up with Polish titles. Confusing.
4. Reloading with CTRL-R fixes everything - whole Tree View shows titles in current locale.

Is this the intended behavior or have I done something wrong? Editing is fine and it's only a display issue with the Tree View, but it's very confusing for the editor.

**Comment by bumbus** [comment]
Is there a fix for this in progress? Would be cool to have this in the official repo instead of local fixes.

**Comment by tractorcow** [comment]
The module used to just refresh the whole page (making everything refreshed) but it was requested that the behaviour is changed to use the standard soft ajax refresh, so it'll need to be fixed in core if we want to keep this.

**Comment by promotion** [comment]
Yep, this is something really important to be fixed or at least controlled via config.yml  so that we could easily choose - AJAX update or Reload. We are all awaiting :) Thanks

**Comment by tractorcow** [comment]
Yeah, I'll make it an option... or would someone like to make a pull request in the mean time? (I'm likely not to get around to this any time soon).

**Comment by tractorcow** [comment]
Here's the commit that made the loading via ajax... the change would partially be a reversion of the existing code, plus an additional option to switch between the old / new functionality.

https://github.com/tractorcow/silverstripe-fluent/commit/77d98e0f489db8ec74ad2d091b3b292c4bfb7d1a
